### ISSUE TITLE
xcms fillPeaks.MSW 

### ISSUE THREAD

**Issue by Pemjon** [sneumann/xcms#45] opened 2016-08-03 08:42 UTC
Hi 

I have been trying to use the fillPeaks.MSW function in your xcms package, to look at some direct infusion data. The code is as follows below, and I keep getting the same error which is 

Xset<-xcmsSet(method="MSW", files=msFiles, scales=c(1,4,9),nearbyPeak=T, verbose.columns = FALSE, winSize.noise=500, SNR.method="data.mean", snthr=5)
XsetG<-group(Xset, method="mzClust", mzppm=5)
XsetGf<-fillPeaks(XsetG, method="MSW")

Error in seq.default((mmzpos - mrange[1]), (mmzpos + mrange[2])) : 
'from' must be of length 1 

I opened the code for this function in R to trouble shoot this and I couldn't fix the problem, only managed to change the error I am not sure what mrange is but appears to be an argument default set to c(0,0) in the function. mmzpos seems to vary having either one or two values which is extracted using 
mmzpos <- mzpos[which(lcraw@env$intensity[mzpos] == max(lcraw@env$intensity[mzpos]))].

If you need any further information please feel free to ask

**Comment by sneumann** [comment] 2016-08-03 10:39
Hi, let's clarify what you mean by direct infusion. Is it a 30sec measurement of some syringe-injected sample ? Resulting in a raw file with, say, 30 scans ? MSW was designed for input files with exactly *one* spectrum. Yours, Steffen

**Comment by Pemjon** [comment] 2016-08-03 15:03
Hi Steffen 

It is a 40 second run of the syringe injected sample with 30 scans per sample. 

Thanks for responding so quickly 

Jon

**Comment by Pemjon** [comment] 2016-08-03 16:26
Hi Steffen

It is a 40 second run of the syringe injected sample with 30 scans per
sample.

Thanks for responding so quickly

Jon

**Comment by sneumann** [comment] 2016-08-03 19:55
So the actual fix is to add a more meaningful error message if n>1 spectra 
are present in the file, which fillPeaks.MSW is not designed to handle,
since it does not know from which scan to take the intensity.

**Comment by Pemjon** [comment] 2016-08-05 08:46
Okay is that the same for the xcmsSet.MSW method as well? Is there a way of obtaining an averaged spectra of the scans before using the fillPeaks.MSW function in R

**Comment by Pemjon** [comment] 2016-08-16 10:38
Hi Steffen 

I have been looking into the original issue that I was having with the fillPeaks.MSW function and because the program doesn't know which intensity value to extract I have added a mean function in the code which appears to fix the problems. Instead of just taking the first scan intensity it will average all the intensities found in that mass range, but I was wondering if the same is true for the xcmsSet (method=MSW) if this also only takes the first scan and if so could the same fix solve the problem? 

 nppos <- nppos + 1
          mzpos <- which(abs(lcraw@env$mz - groupmat[g,"mzmed"]) == min(abs(lcraw@env$mz - groupmat[g,"mzmed"])))
          mmzpos <- mzpos[which(lcraw@env$intensity[mzpos] == max(lcraw@env$intensity[mzpos]))]
          mmzpos<-mean(mmzpos) 
          mmzr <- seq((mmzpos-mrange[1]),(mmzpos+mrange[2]))
          maxo <- max(lcraw@env$intensity[mmzr])
          medMZmin <- median(peakmat[groupindex[[g]], "mzmin"])
          medMZmax <- median(peakmat[groupindex[[g]],"mzmax"])
          minMzpos <- min(which(abs(lcraw@env$mz - medMZmin) ==  min(abs(lcraw@env$mz - medMZmin))))
          maxMzpos <- max(which(abs(lcraw@env$mz - medMZmax) == min(abs(lcraw@env$mz - medMZmax))))
          into = sum(lcraw@env$intensity[minMzpos:maxMzpos])

Also if the peak intensity is only found in a fraction of the scans could this also be attributed to noise? and if so is it worth building into the function a scan number and fraction of scans the peak needs to be present to be counted as a real peak?

Thanks 

Jon

**Comment by sneumann** [comment] 2016-08-16 12:34
The findPeaks.MSW was also just uses one spectrum,
our previous FT-ICR did essentially a single-spectrum. 

Instead of trying to tweak xcms, I'd rather check if some other 
feature extraction tool was developed for direct infusion data. 
And only if that fails to modify xcms. RMassBank was designed
to extract data-dependent MS/MS spectra, and it also had 
the multiplicity filter against noise that you just described. 

Yours, Steffen

**Comment by jorainer** [comment] 2020-10-29 08:04
This is now also fixed with the new user functions.

**Closed by jorainer** 2020-10-29 08:04 UTC
