### ISSUE TITLE
centWave finds peaks/features with rtmin > rtmax

### ISSUE THREAD

**Issue by cdinter** [sneumann/xcms#300] opened 2018-07-11 07:21 UTC
Good day,

my problem is as specified in the title. Applying centWave to my data yields a number of peaks with a minimum retention time larger than the maximum retention time of that peak. This makes no sense to me.

Take a look at rtmin and rtmax for peaks[idx, ] in my code below.
The code I used:
```
# get path to data1
datadir1 <- readline(
  prompt = "Type in path to your first sample group.")
datadir1 <- gsub("\\\\", "/", datadir1)

mzMLfiles1 <- dir(
  path = datadir1,
  pattern = ".mzML", recursive = FALSE, include.dirs = TRUE)

mzMLfiles1 <- paste(
  datadir1,
  mzMLfiles1, sep = "/")

# get path to data2
datadir2 <- readline(
  prompt = "Type in path to your secound sample group.")
datadir2 <- gsub("\\\\", "/", datadir2)

mzMLfiles2 <- dir(
  path = datadir2,
  pattern = ".mzML", recursive = FALSE, include.dirs = TRUE)

mzMLfiles2 <- paste(
  datadir2,
  mzMLfiles2, sep = "/")


nSamples1 <- length(mzMLfiles1)
nSamples2 <- length(mzMLfiles2)
nSamples <- nSamples1 + nSamples2



# load data
require(xcms)

pd <- data.frame(sample_names = sub(basename(c(mzMLfiles1, mzMLfiles2)), 
                                    pattern = ".mzML", replacement = "", 
                                    fixed = TRUE), 
                 sample_group = c(rep(basename(datadir1), nSamples1), 
                                  rep(basename(datadir2), nSamples2)), 
                 stringsAsFactors = FALSE)

rawData <- readMSData(files = c(mzMLfiles1, mzMLfiles2), 
                      pdata = new("NAnnotatedDataFrame", pd),
                      mode = "onDisk", centroided. = TRUE)

rawMS1 <- filterMsLevel(rawData, msLevel. = 1)
# rawMS2 <- filterMsLevel(rawData, msLevel. = 2)



# centWave
cwp <- CentWaveParam(peakwidth = c(10, 210), 
                     snthresh = 5, 
                     prefilter = c(3, 10),
                     mzdiff = 0.01)
chromData <- findChromPeaks(rawMS1, param = cwp)



# obiwarp
owp <- ObiwarpParam(centerSample = 6)
adjData <- adjustRtime(chromData, param = owp)



# density grouping
pdp <- PeakDensityParam(sampleGroups = rawData$sample_group,
                        binSize = 0.025)
groupData <- groupChromPeaks(adjData, param = pdp)



# problem
peaks <- chromPeaks(chromData)
idx <- which(peaks[, 5] > peaks[, 6])
idx
[1]  8817 10021 10022 10023 10024 10025 10026 10027 10028 14847 14943 21401
[13] 21402 21403 21404 21993 22434


peaks[idx, ]
            mz    mzmin    mzmax      rt   rtmin   rtmax      into intb
 [1,] 405.8168 405.8090 405.8214 203.523 232.073 202.673  9.686499    0
 [2,] 463.8381 463.8292 463.8466 106.598 163.427 107.538  1.227678    0
 [3,] 463.8381 463.8292 463.8466 106.598 180.108 107.538  1.124604    0
 [4,] 463.8381 463.8292 463.8466 106.598 182.220 107.538  1.104383    0
 [5,] 463.8381 463.8292 463.8466 106.598 190.903 107.538  1.123261    0
 [6,] 463.8381 463.8292 463.8466 106.598 204.662 107.538  1.193380    0
 [7,] 463.8381 463.8292 463.8466 106.598 210.244 107.538  1.199801    0
 [8,] 463.8381 463.8292 463.8466 106.598 212.790 107.538  1.188559    0
 [9,] 463.8381 463.8292 463.8466 106.598 214.511 107.538  1.185414    0
[10,] 398.3050 398.2990 398.3097 125.965 128.485 125.965  1.747040    0
[11,] 470.3690 470.3572 470.3784 125.965 127.645 125.125  2.380822    0
[12,] 283.7186 283.7169 283.7272 123.693 153.670 123.693  5.486873    0
[13,] 283.7186 283.7169 283.7272 123.693 147.572 123.992  6.145631    0
[14,] 283.7186 283.7169 283.7272 123.693 151.030 123.992  5.536839    0
[15,] 283.7186 283.7169 283.7272 123.693 152.212 123.992  5.406981    0
[16,] 188.2282 188.2254 188.2293 201.628 230.285 200.796 10.865932    0
[17,] 202.2162 202.2137 202.2180 200.796 225.690 200.796 16.026810    0
           maxo sn sample is_filled
 [1,] 0.8318028 41      3         0
 [2,] 0.6170526 17      4         0
 [3,] 0.6170526 17      4         0
 [4,] 0.6170526 17      4         0
 [5,] 0.6170526 17      4         0
 [6,] 0.6170526 17      4         0
 [7,] 0.6170526 17      4         0
 [8,] 0.6170526 17      4         0
 [9,] 0.6170526 17      4         0
[10,] 0.7455916 55      5         0
[11,] 0.7995777 81      5         0
[12,] 0.6316331 16      7         0
[13,] 0.6316331 16      7         0
[14,] 0.6316331 16      7         0
[15,] 0.6316331 16      7         0
[16,] 0.7668933 52      7         0
[17,] 0.9656341 83      7         0
```

This even propagates into the featureDefinitions

```
featDef <- featureDefinitions(chromData)
featDef[316, ]
DataFrame with 1 row and 10 columns
                  mzmed            mzmin            mzmax           rtmed
              <numeric>        <numeric>        <numeric>       <numeric>
FT0316 283.718639414681 283.717977127718 283.718639414681 122.70231628418
                 rtmin           rtmax    npeaks        X5       X50
             <numeric>       <numeric> <numeric> <numeric> <numeric>
FT0316 122.70231628418 124.30099999998         5         0         2
                                    peakidx
                                     <list>
FT0316 c(18064, 21401, 21402, 21403, 21404)

```
As you can tell the peaks defining this feature (except peak 18064) are included in the 'idx' from above in the code.

I thought this might be due to jumbled retention times of my data, but this does not seem to be the case:
```
which(diff(rtime(chromData)) <= 0)
F2.S00001 F3.S00001 F4.S00001 F5.S00001 F6.S00001 F7.S00001 F8.S00001
    11841     23670     35729     47639     59554     71456     83375
```

Am I missing something here and this is intended behaviour?

Thank you very much for any help you can provide.

Kind regards

PS: my sessionInfo()

> > sessionInfo()
> R version 3.5.0 (2018-04-23)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.04.4 LTS
> 
> Matrix products: default
> BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
> LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] parallel  stats     graphics  grDevices utils     datasets  methods
> [8] base
> 
> other attached packages:
> [1] xcms_3.3.3          MSnbase_2.6.1       ProtGenerics_1.12.0
> [4] mzR_2.14.0          Rcpp_0.12.17        BiocParallel_1.14.1
> [7] Biobase_2.40.0      BiocGenerics_0.26.0
> 
> loaded via a namespace (and not attached):
>  [1] RColorBrewer_1.1-2     pillar_1.2.3           compiler_3.5.0
>  [4] BiocInstaller_1.30.0   DEoptimR_1.0-8         plyr_1.8.4
>  [7] iterators_1.0.9        zlibbioc_1.26.0        MALDIquant_1.17
> [10] digest_0.6.15          preprocessCore_1.42.0  tibble_1.4.2
> [13] gtable_0.2.0           lattice_0.20-35        rlang_0.2.1
> [16] Matrix_1.2-14          foreach_1.4.4          S4Vectors_0.18.3
> [19] IRanges_2.14.10        multtest_2.36.0        stats4_3.5.0
> [22] grid_3.5.0             robustbase_0.93-1      impute_1.54.0
> [25] survival_2.42-3        XML_3.98-1.11          RANN_2.5.1
> [28] limma_3.36.2           ggplot2_2.2.1          splines_3.5.0
> [31] scales_0.5.0           pcaMethods_1.72.0      codetools_0.2-15
> [34] MASS_7.3-50            MassSpecWavelet_1.46.0 mzID_1.18.0
> [37] colorspace_1.3-2       affy_1.58.0            lazyeval_0.2.1
> [40] munsell_0.5.0          doParallel_1.0.11      vsn_3.48.1
> [43] affyio_1.50.0

**Comment by jotsetung** [comment] 2018-07-16 03:29
Thanks @cdinter for the very detailed information you provided. Indeed, this does not make any sense at all. Can you please check if you see this problem already right after peak detection (i.e. after the `findChromPeaks` call)? This would help defining whether *centWave* or *obiwarp* leads to this unexpected behavior.

**Comment by cdinter** [comment] 2018-07-16 10:35
This should be what I am already doing. The result of findChromPeaks is saved in chromData and the result of obiwarp is saved in adjData. And chromPeaks is called on the chromData object. Thanks for your reply!

**Comment by jotsetung** [comment] 2018-07-16 12:01
Sorry, didn't realize that. Would it be possible for you to share one of your files that results in these strange peaks (i.e. one of sample 3, 4, 5, 7)?

**Comment by stanstrup** [comment] 2018-07-16 12:07
There also seem to be a similar problem as in https://github.com/sneumann/xcms/issues/284. In row 2-9 above the peaks are all in the same file; same mz, same rt, only different rtmin.

**Comment by cdinter** [comment] 2018-07-16 13:08
@jotsetung Yes I can share one of those files with you. What is the best way to do this? email?

**Comment by stanstrup** [comment] 2018-07-16 13:16
Zip and attach here? Max is 25 MB.

**Comment by jotsetung** [comment] 2018-07-16 13:35
or sharing *via* dropbox or alike?

**Comment by jotsetung** [comment] 2018-08-06 08:53
Ah, sorry, was probably too late (holidays), link seems to be dead now.

**Comment by cdinter** [comment] 2018-08-06 11:26
Yes, the link was only valid until end of the month.
[Here](https://fz-juelich.sciebo.de/s/HZ3oE4r73g5H55w) is a new link.

**Comment by jotsetung** [comment] 2018-08-08 06:42
The problem was in the postprocessing of the identified chromatographic peaks, specifically in the step narrowing the detected peaks by skipping zero intensities at the boundaries. The function used to identify zeros was `xcms:::findEqualGreatedUnsorted(pd, 1)` with `pd` being the individual intensity values of the peak (the full code is shown below). This function was used to search for the first and and the last value in `pd` being `>= 1` and the boundaries were re-adjusted accordingly. The problem was that in your case the peak intensities are very low (even below 1) and for peaks with many such low intensity values the code below switched the lower and upper rt boundary.

```r
            ## narrow down peak rt boundaries by skipping zeros
            lm.l <- xcms:::findEqualGreaterUnsorted(pd, 1)
            lm.l <- max(1, lm.l - 1)
            lm.r <- xcms:::findEqualGreaterUnsorted(rev(pd), 1)
            lm.r <- max(1, lm.r - 1)
            lm <- lm + c(lm.l - 1, -(lm.r - 1) )
```

I'll simplify/fix the code above and perform tests to ensure that the changes yield valid results.

**Comment by cdinter** [comment] 2018-08-08 10:03
Yes, I'm aware of these unusally low intensities. They seem to be caused by selecting 'vendor peak picking' from the msConvert, when converting from .wiff to .mzML

**Comment by SiggiSmara** [comment] 2018-08-08 10:13
UI.. just FIY, we (including @jotsetung ) have observed a very bad performance of peak picking in general with msConvert, and specifically wiff vendor peack picking.  Our workflow (we also have sciex data) is exporting profile data then spectral averaging and centroiding in XCMS and saving that as a new mzML file before doing anything on the features.

**Comment by jotsetung** [comment] 2018-08-08 10:45
I've fixed the peak narrowing. Using `xcms` before fixing I got the following peaks with `rtmin > rtmax`:

```r
bad_idx <- which(chromPeaks(chromData_old)[, "rtmax"] <
                 chromPeaks(chromData_old)[, "rtmin"])
chromPeaks(chromData_old)[bad_idx, ]

             mz    mzmin    mzmax      rt   rtmin   rtmax      into intb
CP1811 283.7186 283.7169 283.7272 123.693 153.670 123.693  5.486873    0
CP1812 283.7186 283.7169 283.7272 123.693 147.572 123.992  6.145631    0
CP1813 283.7186 283.7169 283.7272 123.693 151.030 123.992  5.536839    0
CP2402 188.2282 188.2254 188.2293 201.628 230.285 200.796 10.865932    0
CP2844 202.2162 202.2137 202.2180 200.796 225.690 200.796 16.026810    0
            maxo sn sample is_filled
CP1811 0.6316331 16      1         0
CP1812 0.6316331 16      1         0
CP1813 0.6316331 16      1         0
CP2402 0.7668933 52      1         0
CP2844 0.9656341 83      1         0
```

with the first 3 overlapping (i.e. representing the same signal). After the fix I get the following peaks in the respective m/z ranges:
```r
mzr <- chromPeaks(chromData_old)[bad_idx[1], c("mzmin", "mzmax")]
chromPeaks(chromData, mz = mzr)

             mz    mzmin    mzmax      rt   rtmin   rtmax     into intb
CP1811 283.7186 283.7169 283.7272 123.693 123.693 147.859 6.331488    0
            maxo sn sample is_filled
CP1811 0.6316331 16      1         0

## Next one:
mzr <- chromPeaks(chromData_old)[bad_idx[4], c("mzmin", "mzmax")]
chromPeaks(chromData, mz = mzr)

             mz    mzmin    mzmax      rt   rtmin   rtmax    into intb
CP2400 188.2282 188.2254 188.2293 201.628 200.498 230.566 11.0277    0
            maxo sn sample is_filled
CP2400 0.7668933 52      1         0

## And the last one:
mzr <- chromPeaks(chromData_old)[bad_idx[5], c("mzmin", "mzmax")]
chromPeaks(chromData, mz = mzr)

             mz    mzmin    mzmax      rt   rtmin   rtmax      into     intb
CP2841 202.2161 202.2156 202.2168 130.764 117.484 139.202 141.14161 119.5447
CP2842 202.2162 202.2137 202.2180 200.796 200.498 225.980  16.32708   0.0000
             maxo sn sample is_filled
CP2841 30.8934044 30      1         0
CP2842  0.9656341 83      1         0
## Note that there are 2 peaks in that m/z slice. The second corresponds to the one with
## faulty retention times prior fixing
```

All peaks have now `rtmax > rtmin` and all peaks (except the *problematic* ones above) are identical before and after fixing the bug.

@cdinter can you please install the new `xcms` using `devtools::install_github("sneumann/xcms")` and check if it resolves the problem you reported?

**Comment by jotsetung** [comment] 2018-08-08 11:37
Regarding @SiggiSmara's comment on the centroiding above: have a look at https://jotsetung.github.io/metabolomics2018/xcms-preprocessing.html#23_centroiding_of_profile_ms_data that illustrates how to perform centroiding in R using `MSnbase`. It is also worth evaluating the different `pickPeaks` options (have a look at the help `?pickPeaks`), in particular the `refineMz` parameter.

**Comment by cdinter** [comment] 2018-08-14 13:47
I installed the new xcms and indeed, there no longer are any peaks with rtmin > rtmax. 
And thanks for the info about centroiding with msnbase, I wasnt aware the possibility existed.
Thank you very much!

**Comment by jotsetung** [comment] 2018-08-16 10:09
I guess we can now close the issue - feel free to reopen if needed or if something is unclear.

**Closed by jotsetung** 2018-08-16 10:09 UTC
