### ISSUE TITLE
chromatogram method for XCMSnExp objects does not work?

### ISSUE THREAD

**Issue by mjhelf** [sneumann/xcms#221] opened 2017-09-15 20:12 UTC
Hi, I am trying to work with the new interface, and it is great so far!

I noticed a problem with the chromatogram method for XCMSnExp objects:
```
centroidFilesObj <- readMSData(centroidFiles, pdata = NULL, verbose = isMSnbaseVerbose(),
                          centroided. = T,
                          smoothed. = NA, mode = "onDisk")

#This works:
centroidOndiskchrom <- xcms::chromatogram(centroidFilesObj,
                                          rt = matrix(c(150,160,200,210),ncol=2 ),
                                          mz = matrix(c(150,160,200,210),ncol=2 ), 
                                          BPPARAM = SnowParam(workers = 1))

plot(centroidOndiskchrom)

centroidXset <- findChromPeaks(centroidFilesObj,
                               CentWaveParam(),
                               BPPARAM = SnowParam(workers = 1), 
                               return.type = "XCMSnExp")

#This fails:
centroidXsetChrom <- xcms::chromatogram(centroidXset,
                                        rt = c(150,200),
                                        mz = c(300,320))
```

```
Error: BiocParallel errors
  element index: 1, 2
  first error: could not find function "Chromatogram"
```
Of course this is more relevant for objects after RT correction.
I get the same error if I remove the BPPARAM setting from the `chromatogram `method call for `OnDiskMSnExp`.

I think the reason that chromatogram fails for the `XCMSnExp` is that there is no argument for `BPPARAM` passed on to the `OnDiskMSnExp` `chromatogram` method?

From the xcms3 source code (methods-XCMSnExp.R):
```
setMethod("chromatogram",
          signature(object = "XCMSnExp"),
          function(object, rt, mz, adjustedRtime = hasAdjustedRtime(object),
                   aggregationFun = "sum", missing = NA_real_) {
            ## Coerce to OnDiskMSnExp.
            if (adjustedRtime)
              adj_rt <- rtime(object, adjusted = TRUE)
            object <- as(object, "OnDiskMSnExp")
            if (adjustedRtime) {
              ## Replace the original rtime with adjusted ones...
              object@featureData$retentionTime <- adj_rt
            }
            chromatogram(object, rt = rt, mz = mz,
                         aggregationFun = aggregationFun,
                         missing = missing)
          })
```

SessionInfo:
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 15063)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xcms_2.99.7         MSnbase_2.3.11      ProtGenerics_1.9.0  mzR_2.11.8          Rcpp_0.12.12        BiocParallel_1.11.8 Biobase_2.37.2      BiocGenerics_0.23.1 devtools_1.13.3    

loaded via a namespace (and not attached):
 [1] compiler_3.4.1         BiocInstaller_1.27.4   RColorBrewer_1.1-2     plyr_1.8.4             iterators_1.0.8        zlibbioc_1.23.0        MALDIquant_1.16.4      digest_0.6.12         
 [9] memoise_1.1.0          tibble_1.3.4           preprocessCore_1.39.3  gtable_0.2.0           lattice_0.20-35        rlang_0.1.2            Matrix_1.2-10          foreach_1.4.3         
[17] withr_2.0.0            S4Vectors_0.15.7       IRanges_2.11.15        stats4_3.4.1           multtest_2.33.0        grid_3.4.1             impute_1.51.0          snow_0.4-2            
[25] survival_2.41-3        XML_3.98-1.9           RANN_2.5.1             limma_3.33.9           ggplot2_2.2.1          MASS_7.3-47            splines_3.4.1          scales_0.5.0          
[33] pcaMethods_1.69.0      codetools_0.2-15       MassSpecWavelet_1.43.0 mzID_1.15.0            colorspace_1.3-2       affy_1.55.0            lazyeval_0.2.0         munsell_0.4.3         
[41] doParallel_1.0.10      vsn_3.45.2             affyio_1.47.1
```

Thank you, best,

Max

**Comment by jotsetung** [comment] 2017-09-18 04:07
thanks for the feedback! I'll look at it. Shouldn't be a problem with the missing parameter, looks more like a problem with the package's namespace.

**Comment by jotsetung** [comment] 2017-09-18 08:34
It is strange indeed. I've now added the `BPPARAM` argument to `chromatogram,XCMSnExp`.

Could you please try:
1) call `chromatogram` without `xcms::`? xcms has only the `chromatogram,XCMSnExp` implemented, while `chromatogram,MSnExp` is defined in `MSnbase`.
2) use `SerialParam()` instead of `SnowParam`. Snow-based parallel processing starts a new `R` instance for each core/worker. Could be that not all libraries are loaded in that new R (just guessing).
3) install the newest xcms from github (`devtools::install_github("sneumann/xcms", ref = "xcms3")`) and retry.

**Comment by mjhelf** [comment] 2017-09-18 20:41
Than you for looking into it!

1. omission of xcms:: does not help.
2. SerialParam did not solve the problem.
3. Reinstalled xcms from gitHub and now it works, as long as the BPPARAM parameter is entered for the `chromatogram, XCMSnExp` call. Would you consider setting a default value for BPPARAM for convenience?

Thanks for your help!

**Comment by jotsetung** [comment] 2017-09-19 11:48
Thanks for testing! 
I did already set the `BPPARAM` argument to its default value (`BPPARAM = bpparam()`). Could be that I did not push that in the previous version - please re-install from `devtools::install_github("sneumann/xcms", ref = "xcms3")` to ensure you have the latest (bleeding edge) version.

My problem is that I can not reproduce the error, at least not with the test files and on Linux. Once I have access againt to my Windows test machine I'll try there. Also I don't understand where this problem is coming from, but it's sometimes surprising which and how S4 methods are dispatched.

**Comment by mjhelf** [comment] 2017-09-19 15:35
Hm, I reinstalled xcms again, and I still need to specify BPPARAM to make it work. Maybe it is just a quirk of my system? Shouldn't have anything to do with the filenames (e.g. dashes) or MS2 spectra being present? 

```
##WORKS NOW!
d> centroidXsetChrom <- chromatogram(centroidXset,
+                                         rt = c(150,200),
+                                         mz = c(300,320),
+                                   BPPARAM = SerialParam()
+                                   )
d> centroidXsetChrom 
Chromatograms with 1 row and 2 columns
     161202-07_N2-1_MeOH_pel_pos_MS2_PO_ex.mzXML 161202-07_N2-1_MeOH_pel_pos_MS2_PO_hi.mzXML
                                  <Chromatogram>                              <Chromatogram>
[1,]                                  length: 21                                  length: 22
phenoData with 1 variables

##STILL FAILS:
d> centroidXsetChrom <- chromatogram(centroidXset,
+                                         rt = c(150,200),
+                                         mz = c(300,320)
+                                   )
Error: BiocParallel errors
  element index: 1, 2
  first error: could not find function "Chromatogram"
```

**Comment by jotsetung** [comment] 2017-09-20 09:04
I tried now on my Windows test machine with R-3.4.1 and xcms 2.99.6 and xcms 2.99.7 and I can not reproduce the error. It is very strange. The only thing I can still do is to change the `Chromatogram` call in `MSnbase` to a `MSnbase::Chromatogram`. Eventually that might do it.

**Comment by jotsetung** [comment] 2018-06-19 13:28
Closing the issue because it should be fixed by now - feel free to reopen if the problem persists.

**Closed by jotsetung** 2018-06-19 13:28 UTC
