### ISSUE TITLE
Direct infusion data with multiple scans and MSW

### ISSUE THREAD

**Issue by joannawolthuis** [sneumann/xcms#237] opened 2017-11-08 14:08 UTC
Dear devs,

First of all, thank you for your hard work on this package! I'm really excited about the MassSpecWavelet method, and have some questions on using it on my data. I've been digging through some older threads on fillpeaks.MSW, findpeaks.MSW, and was wondering:

1 - Is it an issue that my mzXML file contains multiple scans? Specifically, 150 in positive and 150 in negative mode (I use the scanrange argument in xcmsSet to split by mode when processing). 

2 - When adding my file to an xcmsSet: are these individual scans in my selected scanrange averaged or summed before executing findpeaks.MSW? Or does it only grab the first scan and go from there? Same for fillpeaks - I'm noticing that it does fill without errors, but the filled intensities are really high and look like : 51001, 51002, 51003, looks rather dangerously high to be a fill-with-noise result.

3 - Is there any way to sum the intensities over the 150 scans into 'one' spectrum and work from there, if the above points are indeed issues? I found the getSpec function which seems like a good point to start from, but I am also somewhat new to Mass spec, so I may be missing essential metadata that needs to be changed as well here. Any suggestions are welcome - I'd love to use the wavelet approach somehow...

Thank you :-)

Kind regards,

Joanna

**Comment by jotsetung** [comment] 2017-11-08 15:05
Dear Joanna,

first of all, I've never had any direct injection data myself - but I will try to answer your questions as much as I can.

1) well, I think it might be an issue. AFAIK xcms expects to get single spectrum files. The problem is that the `findPeaks.MSW` function does not check this (yet - seems to be a bug) and it treats the mz and intensity values as if they were from a single spectrum.

2) See also above - not it is not summing or averaging spectra.

3) Summing intensities over the 150 scans - that's interesting, and might be a nice addition but AFAIK that is not possible yet.

I would now suggest the following:
1) Install a recent R (R-3.4.2) and install the newest Bioconductor version (3.6) and the newest xcms:
```r
source("https://bioconductor.org/biocLite.R")
biocLite("xcms")
```

you should now have `xcms` version 3. Here please browse the vignettes of the package (either with `help.start()` and browsing to the xcms help page or:
```r
## General xcms vignette
vignette("xcms")

## direct injection related
vignette("xcms-direct-injection", package = "xcms")

```

This describes the new user interface of `xcms` that, in my opinion, helps also with your data: you can now easily subset your data set/file into single-spectra objects with `[]`:
```r
## Assume your file with the 150 spectra is called raw_data, you can
## subset it to the first spectrum using:
raw_data_1 <- raw_data[1]

## And you can perform the peak detection on that. To get spectrum 2 ... 150, just use
## the index to subset it.
```

Hope this helps

**Comment by joannawolthuis** [comment] 2017-11-08 15:18
Hi Johannes, Thank you for your swift reply! I will try out what you posted, I just have one question in the meantime. I did the following to test out what ends up in the xcmsSet when doing this:

a <- xcmsSet(method="MSW",
            files=myfiles[1],
            scanrange = c(20,21),
            snthresh=3,
            nearbyPeak=T)

b <- xcmsSet(method="MSW",
            files=myfiles[1],
            scanrange = c(20,31),
            snthresh=3,
            nearbyPeak=T)

> a
An "xcmsSet" object with 1 samples

Time range: -1--1 seconds (0-0 minutes)
Mass range: 72.0807-521.2357 m/z
Peaks: 277 (about 277 per sample)
Peak Groups: 0 
Sample classes: MZXML 

Peak picking was performed on MS1.
Scan range limited to  20 - 21 
Profile settings: method = bin
                  step = 0.1

Memory usage: 0.0332 MB
> b
An "xcmsSet" object with 1 samples

Time range: -1--1 seconds (0-0 minutes)
Mass range: 72.0807-518.321 m/z
Peaks: 1650 (about 1650 per sample)
Peak Groups: 0 
Sample classes: MZXML 

Peak picking was performed on MS1.
Scan range limited to  20 - 31 
Profile settings: method = bin
                  step = 0.1

Memory usage: 0.159 MB

----- 

So using more scans does end up with more peaks being called - I was wondering what exactly happens here to combine the scans to end up with more peaks, are they merged first? And if there is overlap between scans, summed/averaged? Something is happening and I'd love to know what, perhaps I could also still use the peaks called in this way :-) 

I think with the method you just named above I'd have to choose to use the highest intensity scan, per mode, per sample (although it feels like a waste of the other 149 scans..), or find a way to call peaks on all scans, then grouping the scans to get one grouped matrix per file... and then grouping those grouped peaks between files, which I don't think is supported and may get messy ; w; 

Thank you!

Kind regards,

Joanna

**Comment by joannawolthuis** [comment] 2017-11-08 15:36
Thank you for clarifying that! I agree that that sounds rather wrong yes, I'm happy I found out now and that fillPeaksMSW threw an error (if it hadn't, perhaps I had realised nothing up till publishing, eek!).

I will try this for now by picking the highest signal scan per mode per sample (and maybe play around with grouping scans using mzClust.. maybe finding some magic way to turn that into a new xcmsSet :P). And I did see the update yes! Looks exciting :-) I will swap over to make use of your newer functionality ASAP.

**Comment by sneumann** [comment] 2017-11-09 06:33
Hi, MSW was indeed written for a single scan, and the correct behaviour would be to cry foul and `stop("More than one scan in xcmsRaw")` . Yours, Steffen

**Comment by jotsetung** [comment] 2017-11-09 07:08
Yes - the *new* user interface throws an error if there is more than one spectrum, only, in the old interface (i.e. the `findPeaks.MSW`) did not check for that. I'll add that as soon as I find the time for it.

**Comment by joannawolthuis** [comment] 2017-11-10 12:22
Hi! Last time I tried with the new interface I got through findPeaks without error, but fillpeaks.MSW did throw one about the multiple spectra.

Meanwhile I have been experimenting a bit with summing the results of all scans (with a variant on getSpec that sums instead of averages) and exporting that to CDF format as a single spectrum, then reloading it as xcmsSet again. This -seems- to work OK, but I'd have to check if this is possible in the new interface. I do see some what fels like strange filled values after fillPeaks, really high values, I wonder if that is going OK...

In case you were interested in something like this for future updates, the options I was imagining could work are:

- Summing / averaging over all scans and calling peaks over that new spectrum
- Calling peaks on each spectrum separately, then grouping those as a new 'spectrum'
- Picking one scan (however discarding quite a bit of your data by doing so) which works now but I'd prefer not do do forever.

Thank you for your replies!

PS: Here is the script I made for summing, it's really basic but a first try.

```
files = list.files(folder, pattern="\\.mzXML", full.names = T)
f <- files[i]

getSumSpec = function (object, ...) 
{
  sel <- profRange(object, ...)
  print(sel)
  scans <- list(length(sel$scanidx))
  uniquemz <- numeric()
  for (i in seq(along = sel$scanidx)) {
    currScan <- getScan(object, sel$scanidx[i], sel$mzrange)
    uniquemz <- unique(c(uniquemz, currScan[, "mz"]))
    scans[[i]] <- currScan
  }
  uniquemz <- sort(uniquemz)
  intmat <- matrix(nrow = length(uniquemz), ncol = length(sel$scanidx))
  for (i in seq(along = sel$scanidx)) {
    scan <- getScan(object, sel$scanidx[i], sel$mzrange)
    intmat[, i] <- approx(scan, xout = uniquemz)$y
  }
  # remove NA rows
  intmat[is.na(intmat)] <- 0
  # --------------
  points <- cbind(mz = uniquemz, intensity = rowSums(intmat))
  points
}

# load raw file, specify scan range here
xraw_pos <- xcmsRaw(f,profstep = 0.01,scanrange = c(10,150))

# merge profiles
pos_profile <- xraw_pos@env$profile

p <- pos_profile[,1]
for(i in 2:ncol(pos_profile)){
  vec <- pos_profile[,i]
  p = p + vec
}
pmat <- matrix(p)

# merge scans
scansum <- as.data.frame(getSumSpec(xraw_pos))
xr_sum <- xraw_pos
xr_sum@env$mz <- scansum$mz
xr_sum@env$intensity <- scansum$intensity
xr_sum@env$profile <- pmat
xr_sum@scanindex <- as.integer(0)
xr_sum@scantime <- xr_sum@scantime[1]
xr_sum@tic <- sum(scansum$intensity)
xr_sum@polarity <- as.factor("positive")
xr_sum@acquisitionNum <- as.integer(1)
xr_sum@scanrange <- 1

# write to cdf
cdf_pos = file.path(outfolder,
                    gsub(basename(f),
                         pattern="\\.mzXML",
                         replacement="_pos.cdf"))

write.cdf(xr_sum,file=cdf_pos)

# load in and call peaks
xset_pos <- xcmsSet(method="MSW",
                    files=cdf_pos,
                    scales=scale,
                    snthresh=3,
                    nearbyPeak=T)

npeaks <- nrow(xset_pos@peaks)

# --- report back ---
print(paste("Found", npeaks, "peaks in file", basename(f), "in positive mode!", sep=" "))
```

**Comment by carobirer** [comment] 2018-04-10 18:08
Hi everyone. I already used a bit xcms package with lc-ms data, but I try to find the way to use xcms with direct infusion data. I am very interested by this findPeaks.MSW function. I also have direct infusion mass spec data with 100 scans. What is the best way to deal with that? 
1 I was thinking to open this file in xcalibur (I have thermo data) and use their tool to generate an averaged spectrum an export that unique file, transform it in mzml and open it in xcms.
2  follow the script of Joanna and sum or averaged spectrum? 
3 others ideas?

Thanks!

**Comment by sneumann** [comment] 2018-04-10 18:27
Hi, about 3: you might want to check out the proFIA package https://www.ncbi.nlm.nih.gov/pubmed/29036359 Yours, Steffen

**Comment by carobirer** [comment] 2018-04-11 01:12
Thank you very much ! I was looking for something like that since several days. I was always using DI-MS as a key word for the search, I didn't t know that FIA-MS is also used.

**Comment by jotsetung** [comment] 2018-04-11 05:35
Just an update on summing/averaging spectra: we have now included the `combineSpectra` function in `MSnbase` (current developmental version - will be released with Bioconducto 3.7 in May) that can be used to, as the name says, combine the signal from multiple spectra into a single spectrum. Although not tested on FIA data, I think this could be useful.

**Comment by carobirer** [comment] 2018-04-19 16:55
Hi all, 
Thank you for your help. I tried to use proFIA first, and proFIA is very specific to FIA data and could not be used with direct infusion data. I have ms data acquired by direct infusion with the NanoChip technology with the Triversa Nanomate Robot of Advion coupled with the Velos mass spectrometer of Thermo. 
For each sample, I have 100 MS1 spectra (and some MS2 of top 6 peaks...) in positive mode and I managed to obtain a main MS1 spectrum, for each sample with combineSpectra function. This function is great!
Because combineSpectra needs a spectrum file in profile mode, I first transformed .raw profile data with proteowizard in .mzml profile with only MS1. I loaded this with readMSData function and transformed it  with the spectra function. Then I wrote a loop to use combineSpectra for multiple samples and I finally obtained a list of spectra files, with one main spectrum for each sample. 
Now, I would like to go back to xcms and follow the workflow for direct infusion data.
`## direct injection related
vignette("xcms-direct-injection", package = "xcms")`
 How can I convert a list of spectra objects into a specific xcms object? Let me know if you have any others suggestions. 

Thank you for your help,

Here is my code

`## 1 loading ms1 profile (proteowizard) data mzml format
file_prof = list.files("/Users/cbirer/Documents/OneDrive/msdata_pitt/data/prof_all", recursive = TRUE, full.names = TRUE)

proffiles = readMSData(file_prof, pdata = NULL, msLevel. = 1,
                       verbose = isMSnbaseVerbose(), centroided. = NA, smoothed. = NA,
                       cache. = 1L, mode = "onDisk")

## 2 make a list of Spectrum objects
spectraprof_file = spectra(proffiles)


ns <- names(spectraprof_file)
samp <- gsub("()\\..+", "\\1", ns)
u <- unique(samp)
## 3 Combine signals from profile-mode spectra of consecutive scans into the values for the main spectrum.
filesprof_comb <- vector("list", length(u))
for (i in seq_along(u)) {
  w <- which(samp==u[i])
  filesprof_comb[[i]] = combineSpectra(x=spectraprof_file[w], mzFun = base::mean, intensityFun = base::mean,
                                       main = floor(length(w)/2L) + 1L, timeDomain = FALSE)
}

`

**Comment by lgatto** [comment] 2018-04-20 07:26
Yes, that's definitely something that could go into `MSnbase`. We could even make it work with a feature variable that defines the spectra to be combined. Something like 

```r
> data(itraqdata) ## MSnExp
> length(itraqdata)
[1] 55
> ## how spectra would be combined
> fData(itraqdata)$combine <- as.integer(seq(1, 10, length.out = 55))
> fData(itraqdata)$combine
 [1]  1  1  1  1  1  1  2  2  2  2  2  2  3  3  3  3  3  3  4  4  4  4  4  4  5
[26]  5  5  5  5  5  6  6  6  6  6  6  7  7  7  7  7  7  8  8  8  8  8  8  9  9
[51]  9  9  9  9 10
> x <- combineSpectra(itraqdata, mzFun = base::mean, fcol = "combine") ## new 
> ## length(x) would be 10
```

**Comment by jotsetung** [comment] 2018-04-20 07:40
OK, so the itraqdata is a direct infusion data?

**Comment by lgatto** [comment] 2018-04-20 08:00
No, I just used this `MSnExp` as an example to illustrate the syntax. It would basically be `MSnExp` (plus a feature variable defining what spectra to combine) as input and a shorter `MSnExp` as output. This would also work:
```r
x %>% combineFeatures(base::mean, fcol = "combine")
```

**Comment by carobirer** [comment] 2018-04-23 14:36
Hi everyone, Thank you so much for your reply. 
Yes it is exactly what I need, to be able to combine spectra within a MSnExp object with a combine vector that define how spectra has to be combine. 
I am happy to share data with you to add to a vignette. Which system will you recommend me in order to send files? Is "we transfer" good for you?
Let me know,

**Comment by carobirer** [comment] 2018-04-23 15:08
"Is calculating the mean good enough for you or would there be a better way to combine the intensities?"
I don t know, and I don t really know what could be a better way to combine intensities? I think it's what people do usually with intensities. At this first step, I think it is good to keep as much as we can mz peaks with their intensities, and after apply the "peak detection" that also remove noise and "correspondence" steps from the direct infusion vignette "grouping FTICR-MS data with xcms". Even if I don t have FTICR-MS data, I think I should follow this vignette.

**Comment by carobirer** [comment] 2018-04-23 20:01
Ok great thank you so much. Let me know how I can help and if you need a test file from me.

**Comment by jotsetung** [comment] 2018-06-20 07:53
I think we can close the issue here in `xcms`. Feel free to reopen if needed.

**Closed by jotsetung** 2018-06-20 07:53 UTC
