### ISSUE TITLE
Potential bug in the function getXcmsRaw

### ISSUE THREAD

**Issue by asmirn1** [sneumann/xcms#44] opened 2016-08-01 15:17 UTC
Hi. Recently, I was working with XCMS taken from **Bioconductor-mirror/xcms** (branch **release-3.3**) and noticed a bug. When I align two samples and plot the aligned peaks with the function getEIC, the returned EICs are the same for both rt="corrected" and rt="raw" parameters. Then I read the source code and, I believe, the problem is in the function getXcmsRaw:

`for(i in 1:length(ret)){

  ## **** I'm skipping some lines here ****

  if(rt == "corrected"){

  ## check if there is any need to apply correction...

     if(all(object@rt$corrected[[i]] == object@rt$raw[[i]])){

         message("No need to perform retention time correction,",

             " raw and corrected rt are identical for ", fn[i])

         ret[[i]]@scantime <- object@rt$raw[[sampidx[i]]]

     }else{

         message(paste0("Applying retention time correction to ", fn[i]))

         ret[[i]]@scantime <- object@rt$corrected[[sampidx[i]]]
     }

  }

}`

I think that the line 
`if(all(object@rt$corrected[[i]] == object@rt$raw[[i]])){`
should be replaced by 
`if(all(object@rt$corrected[[sampidx[i]]] == object@rt$raw[[sampidx[i]]])){`

Otherwise, if I have only two samples and the first one is the reference sample, then length(ret) is always equal to 1 and the condition all(object@rt$corrected[[i]] == object@rt$raw[[i]]) is always satisfied, even if I'm using getEIC to plot the second (aligned) sample.

It's interesting that the branch **devel** from **sneumann/xcms** doesn't use getXcmsRaw in the function getEIC, so it plots the samples correctly. However, getXcmsRaw still has that line `if(all(object@rt$corrected[[i]] == object@rt$raw[[i]])){`

As I understand, you are rewriting XCMS now, and you might not use getXcmsRaw at all in the newer versions of XCMS, but I just wanted to let you know about this issue.

Thank you for your work on XCMS,

Aleksandr

**Comment by sneumann** [comment] 2016-08-01 17:09
Thanks for the notification, perfect timing!. If you could hack this 
into a unitTest checking your expected behaviour 
(and failling if it doesn't) would be awesome,
then we could check this does not bite is in the future.
Yours, Steffen

**Comment by asmirn1** [comment] 2016-08-02 00:16
Steffen,

Unfortunately, I could't create a small XcmsSet object to test the method
getXcmsRaw (maybe you could help me, any aligned XcmsSet object with two
samples would do).

I could provide you with the data I'm running it on, but I'm not sure if it
will be appropriate for RUnit test since it's a bit time consuming.

Aleksandr

**Comment by jotsetung** [comment] 2016-08-02 07:08
I'll have a closer look at this. At first glance it looks that @asmirn1 is right. I'll add some more `RUnit` tests for `getXcmsRaw` and then we'll see.

**Comment by jotsetung** [comment] 2016-08-02 07:40
OK, there is indeed a bug:
```{r}
> library(xcms)
> library(faahKO)
> library(RUnit)
> data(faahko)
> attr(faahko, "filepaths") <- sapply(as.list(basename(attr(faahko, "filepaths"))),
+                                     function(x) system.file("cdf", if (length(grep("ko",x)) > 0) "KO" else  "WT" ,x, package = "faahKO"))
> xsetRaw <- updateObject(faahko)
## Subset to two files.
> xsetRaw <- xsetRaw[, 1:2]

> ## First sample is reference, i.e. no rt adjustment performed
> xs <- retcor(group(xsetRaw), method = "obiwarp", center = 1)
262 325 387 450 512 575 
center sample:  ko15 
Processing: ko16

> ## Second is corrected, first is center:
> checkIdentical(xs@rt$raw[[1]], xs@rt$corrected[[1]])
[1] TRUE
> checkTrue(!all(xs@rt$raw[[2]] == xs@rt$corrected[[2]]))
[1] TRUE 
> ## We get the raw data for the second file; this one was corrected and
> ## thus it's retention time is expected to be different from raw.
> xr2 <- getXcmsRaw(xs, sampleidx = 2, rt = "corrected")
No need to perform retention time correction, raw and corrected rt are identical for /Users/jo/R/R-3.3.1-Bioc3.4-devel/lib/R/library/faahKO/cdf/KO/ko16.CDF
> checkIdentical(xr2@scantime, xs@rt$corrected[[2]])
Error in checkIdentical(xr2@scantime, xs@rt$corrected[[2]]) : FALSE
 
> all(xr2@scantime == xs@rt$raw[[2]])  ## That should be FALSE!
[1] TRUE
```

I've wrapped that into a unit test and will fix the bug in the *devel* branch.

**Comment by jotsetung** [comment] 2016-08-02 07:58
Dear @asmirn1 , @sneumann I fixed this bug in commit https://github.com/sneumann/xcms/commit/e429a1ba876b35cdf6a7e77a5c528be8f91fb3f7.

Aleksandr was completely right. I've now included a RUnit test specifically for this problem and have also updated the *NEWS*; I didn't bump the version though, as I prefer that Steffen does that if he's OK with the changes.

**Comment by sneumann** [comment] 2016-08-22 12:48
This should appear now in xcms-1.49.5 (Due to the way the merging worked, 1.49.4 only lived 
a couple of minutes).

**Comment by jotsetung** [comment] 2016-08-25 09:15
I think it's OK if we close this issue now.

**Closed by jotsetung** 2016-08-25 09:15 UTC
