### ISSUE TITLE
Warning: multiple method tables found - XCMS (3.9.1)

### ISSUE THREAD

**Issue by KelseyChetnik** [sneumann/xcms#459] opened 2020-04-07 20:15 UTC
I'm developing a package that uses xcms as a dependency. I'm building and checking the package on windows using the r-devel version R 4.0.0 alpha. R CMD check produces the following warning:
W  checking whether package 'MetaCleanTest' can be installed (1m 2.9s)NG
   Found the following significant warnings:
     Warning: multiple methods tables found for 'plot'
     Warning: multiple methods tables found for 'impute'

These warnings also show up whenever I load xcms.

Submitting the package to CRAN, I get the following installation error:
* installing *source* package 'MetaCleanTest' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for 'S4Vectors':
 .onLoad failed in loadNamespace() for 'S4Vectors', details:
  call: validObject(.Object)
  error: invalid class "LLint" object: superclass "integer_OR_LLint" not defined in the environment of the object's class
Error: package 'S4Vectors' could not be loaded
In addition: Warning message:
In fun(libname, pkgname) :
  mzR has been built against a different Rcpp version (1.0.3)
than is installed on your system (1.0.4.6). This might lead to errors
when loading mzR. If you encounter such issues, please send a report,
including the output of sessionInfo() to the Bioc support forum at 
https://support.bioconductor.org/. For details see also
https://github.com/sneumann/mzR/wiki/mzR-Rcpp-compiler-linker-issue.
Execution halted
ERROR: lazy loading failed for package 'MetaCleanTest'
* removing 'd:/RCompile/CRANguest/R-devel/lib/MetaCleanTest'
* restoring previous 'd:/RCompile/CRANguest/R-devel/lib/MetaCleanTest'

Could someone please answer the following questions:
1. Are the warnings from R CMD check and the ERROR returned by CRAN's automated pre-test related?
2. What do the warnings / error mean?
3. How can I resolve both of these issues?

sessionInfo:
R version 4.0.0 alpha (2020-03-31 r78116)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252  
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base    

other attached packages:
[1] MetaCleanTest_0.1.0 plotrix_3.7-7      
[3] MLmetrics_1.1.1    

loaded via a namespace (and not attached):
  [1] nlme_3.1-145          
  [2] fs_1.4.1              
  [3] ProtGenerics_1.19.3  
  [4] usethis_1.5.1        
  [5] devtools_2.2.2        
  [6] lubridate_1.7.4      
  [7] doParallel_1.0.15    
  [8] RColorBrewer_1.1-2    
  [9] rprojroot_1.3-2      
 [10] MSnbase_2.13.4        
 [11] tools_4.0.0          
 [12] backports_1.1.5      
 [13] affyio_1.57.0        
 [14] R6_2.4.1              
 [15] rpart_4.1-15          
 [16] BiocGenerics_0.33.3  
 [17] colorspace_1.4-1      
 [18] nnet_7.3-13          
 [19] withr_2.1.2          
 [20] tidyselect_1.0.0      
 [21] prettyunits_1.1.1    
 [22] processx_3.4.2        
 [23] preprocessCore_1.49.2
 [24] compiler_4.0.0        
 [25] MassSpecWavelet_1.53.0
 [26] cli_2.0.2            
 [27] Biobase_2.47.3        
 [28] xml2_1.3.0            
 [29] desc_1.2.0            
 [30] scales_1.1.0          
 [31] DEoptimR_1.0-8        
 [32] robustbase_0.93-6    
 [33] affy_1.65.1          
 [34] callr_3.4.3          
 [35] digest_0.6.25        
 [36] stringr_1.4.0        
 [37] pkgconfig_2.0.3      
 [38] sessioninfo_1.1.1    
 [39] limma_3.43.5          
 [40] rlang_0.4.5          
 [41] rstudioapi_0.11      
 [42] impute_1.61.0        
 [43] generics_0.0.2        
 [44] mzID_1.25.0          
 [45] BiocParallel_1.21.2  
 [46] dplyr_0.8.5          
 [47] ModelMetrics_1.2.2.2  
 [48] magrittr_1.5          
 [49] MALDIquant_1.19.3    
 [50] Matrix_1.2-18        
 [51] Rcpp_1.0.4            
 [52] munsell_0.5.0        
 [53] S4Vectors_0.25.15    
 [54] fansi_0.4.1          
 [55] vsn_3.55.0            
 [56] lifecycle_0.2.0      
 [57] stringi_1.4.6        
 [58] pROC_1.16.2          
 [59] zlibbioc_1.33.1      
 [60] MASS_7.3-51.5        
 [61] pkgbuild_1.0.6        
 [62] plyr_1.8.6            
 [63] recipes_0.1.10        
 [64] grid_4.0.0            
 [65] parallel_4.0.0        
 [66] crayon_1.3.4          
 [67] lattice_0.20-40      
 [68] splines_4.0.0        
 [69] multtest_2.43.1      
 [70] mzR_2.21.1            
 [71] xcms_3.9.1            
 [72] knitr_1.28            
 [73] ps_1.3.2              
 [74] pillar_1.4.3          
 [75] reshape2_1.4.3        
 [76] codetools_0.2-16      
 [77] stats4_4.0.0          
 [78] pkgload_1.0.2        
 [79] XML_3.99-0.3          
 [80] glue_1.4.0            
 [81] remotes_2.1.1        
 [82] BiocManager_1.30.10  
 [83] pcaMethods_1.79.1    
 [84] data.table_1.12.8    
 [85] vctrs_0.2.4          
 [86] foreach_1.5.0        
 [87] testthat_2.3.2        
 [88] gtable_0.3.0          
 [89] RANN_2.6.1            
 [90] purrr_0.3.3          
 [91] assertthat_0.2.1      
 [92] ggplot2_3.3.0        
 [93] xfun_0.12            
 [94] gower_0.2.1          
 [95] prodlim_2019.11.13    
 [96] roxygen2_7.1.0        
 [97] class_7.3-16          
 [98] ncdf4_1.17            
 [99] survival_3.1-11      
[100] timeDate_3043.102    
[101] tibble_3.0.0          
[102] iterators_1.0.12      
[103] memoise_1.1.0        
[104] IRanges_2.21.8        
[105] lava_1.6.7            
[106] ellipsis_0.3.0        
[107] caret_6.0-86          
[108] ipred_0.9-9

**Comment by sneumann** [comment] 2020-04-07 21:39
Hi, could you create the smallest possible package to reproduce ? 
I.e. do you still get the issue with just a DESCRIPTION and NAMESPACE
which depend on xcms ? Yours, Steffen

**Comment by jorainer** [comment] 2020-04-08 06:22
1) The error and the warnings about the multiple methods tables are not related.
2) The warnings mean that there is more than one package being loaded that defines a method for `plot` and `impute`. Loading `xcms` already shows the warning related to the `plot` method - I'm currently investigating how we could get rid of that. Regarding the error, I also got this with `xcms` but could fix that (see below).
3) For the error, I suggest you re-install all main Bioconductor packages (e.g. `BiocManager::install(c("BiocGeneric", "Biobase", "S4Vectors", "IRanges"))`) and try again.

Another question, why are you submitting to CRAN and not to Bioconductor? If you're depending on `xcms` or extending it I would suggest to submit to Bioconductor.

**Comment by sneumann** [comment] 2020-04-08 10:15
Hi, since mzR got kicked out of CRAN, chances for anything depending on xcms to be accepted into CRAN are close to zero. Yours, Steffen

**Comment by jorainer** [comment] 2020-10-21 06:09
Closing the issue now. Feel free to re-open if needed.

**Closed by jorainer** 2020-10-21 06:09 UTC
