### ISSUE TITLE
Error when performing chromatographic peak detection using MatchedFilter algorithm

### ISSUE THREAD

**Issue by leowkx** [sneumann/xcms#305] opened 2018-07-27 03:19 UTC
Hi xcms developers, 

I am trying to perform peak detection using the MatchedFilter method with the following code:

```
mfp <- MatchedFilterParam(binSize = 0.05, fwhm = 6, snthresh = 5, mzdiff = 0.1)
res <- findChromPeaks(dataRaw, param = mfp)
```

But I've been receiving this error:

```
Error in (function (x)  : attempt to apply non-function
In addition: Warning message:
In fun(libname, pkgname) :
  mzR has been built against a different Rcpp version (0.12.16)
than is installed on your system (0.12.18). This might lead to errors
when loading mzR. If you encounter such issues, please send a report,
including the output of sessionInfo() to the Bioc support forum at 
https://support.bioconductor.org/. For details see also
https://github.com/sneumann/mzR/wiki/mzR-Rcpp-compiler-linker-issue.
```
Here is my sessioninfo():

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_Singapore.1252  LC_CTYPE=English_Singapore.1252   
[3] LC_MONETARY=English_Singapore.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Singapore.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xcms_3.2.0          MSnbase_2.6.1       ProtGenerics_1.12.0 mzR_2.14.0         
[5] Rcpp_0.12.18        BiocParallel_1.14.2 Biobase_2.40.0      BiocGenerics_0.26.0

loaded via a namespace (and not attached):
 [1] pillar_1.3.0           compiler_3.5.1         BiocInstaller_1.30.0  
 [4] RColorBrewer_1.1-2     plyr_1.8.4             iterators_1.0.10      
 [7] tools_3.5.1            zlibbioc_1.26.0        MALDIquant_1.18       
[10] digest_0.6.15          preprocessCore_1.42.0  tibble_1.4.2          
[13] gtable_0.2.0           lattice_0.20-35        rlang_0.2.1           
[16] Matrix_1.2-14          foreach_1.4.4          S4Vectors_0.18.3      
[19] IRanges_2.14.10        multtest_2.36.0        stats4_3.5.1          
[22] grid_3.5.1             impute_1.54.0          snow_0.4-2            
[25] survival_2.42-3        XML_3.98-1.12          RANN_2.6              
[28] limma_3.36.2           ggplot2_3.0.0          splines_3.5.1         
[31] scales_0.5.0           pcaMethods_1.72.0      codetools_0.2-15      
[34] MASS_7.3-50            MassSpecWavelet_1.46.0 mzID_1.18.0           
[37] colorspace_1.3-2       affy_1.58.0            lazyeval_0.2.1        
[40] munsell_0.5.0          doParallel_1.0.11      vsn_3.48.1            
[43] crayon_1.3.4           affyio_1.50.0         
```

If it is not obvious what is wrong, I can provide more information like the files I'm using. 

Thank you in advance for any advice!

**Comment by hholm** [comment] 2018-07-27 17:03
Hey loewkx,

One thing to make sure is that your data is an 'OnDiskMSnExp' object.

What is the result of:
`>dataRaw`

**Comment by jotsetung** [comment] 2018-08-06 12:30
@hholm is right, ensure you read your data with `readMSData` and the parameter `mode = "onDisk"` as detailed in the vignette. Also ensure that you don't move the original files after you've read the files.

Can you also provide some more information, such as the number of files you are processing and your parallel processing setup?

**Comment by haihaba** [comment] 2018-08-14 19:04
I have same issue. My data file is mxXML format. It looks it has happened on some files.

```
> xdata <- findChromPeaks(raw_data, param = cwp)
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 23218 regions of interest ... OK: 4325 found.
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 25530 regions of interest ... OK: 7261 found.
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 27058 regions of interest ... OK: 9476 found.
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 26725 regions of interest ... OK: 9088 found.
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 28016 regions of interest ... OK: 10106 found.
Error in (function (x)  : attempt to apply non-function
In addition: Warning messages:
1: In fun(libname, pkgname) :
  mzR has been built against a different Rcpp version (0.12.16)
than is installed on your system (0.12.18). This might lead to errors
when loading mzR. If you encounter such issues, please send a report,
including the output of sessionInfo() to the Bioc support forum at 
https://support.bioconductor.org/. For details see also
https://github.com/sneumann/mzR/wiki/mzR-Rcpp-compiler-linker-issue.
2: package 'MSnbase' was built under R version 3.5.1 
3: package 'Rcpp' was built under R version 3.5.1 
4: package 'BiocParallel' was built under R version 3.5.1 
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 27454 regions of interest ... OK: 9819 found.
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 27467 regions of interest ... OK: 9703 found.
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 27021 regions of interest ... OK: 9689 found.
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 27443 regions of interest ... OK: 9569 found.
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 27170 regions of interest ... OK: 10008 found.
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 27334 regions of interest ... OK: 9597 found.
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 27825 regions of interest ... OK: 9891 found.
Error in (function (x)  : attempt to apply non-function
In addition: Warning messages:
1: In fun(libname, pkgname) :
  mzR has been built against a different Rcpp version (0.12.16)
than is installed on your system (0.12.18). This might lead to errors
when loading mzR. If you encounter such issues, please send a report,
including the output of sessionInfo() to the Bioc support forum at 
https://support.bioconductor.org/. For details see also
https://github.com/sneumann/mzR/wiki/mzR-Rcpp-compiler-linker-issue.
2: package 'MSnbase' was built under R version 3.5.1 
3: package 'Rcpp' was built under R version 3.5.1 
4: package 'BiocParallel' was built under R version 3.5.1 
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 27044 regions of interest ... OK: 10241 found.
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 26908 regions of interest ... OK: 9644 found.
Error in (function (x)  : attempt to apply non-function
In addition: Warning messages:
1: In fun(libname, pkgname) :
  mzR has been built against a different Rcpp version (0.12.16)
than is installed on your system (0.12.18). This might lead to errors
when loading mzR. If you encounter such issues, please send a report,
including the output of sessionInfo() to the Bioc support forum at 
https://support.bioconductor.org/. For details see also
https://github.com/sneumann/mzR/wiki/mzR-Rcpp-compiler-linker-issue.
2: package 'MSnbase' was built under R version 3.5.1 
3: package 'Rcpp' was built under R version 3.5.1 
4: package 'BiocParallel' was built under R version 3.5.1 
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 27738 regions of interest ... OK: 10028 found.
Detecting mass traces at 10 ppm ... OK
Detecting chromatographic peaks in 27590 regions of interest ... OK: 9578 found.
```

My data is shown as 
```
> raw_data
MSn experiment data ("OnDiskMSnExp")
Object size in memory: 9.39 Mb
- - - Spectra data - - -
 MS level(s): 1 
 Number of spectra: 39869 
 MSn retention times: 0:0 - 24:1 minutes
- - - Processing information - - -
Data loaded [Tue Aug 14 14:46:40 2018] 
 MSnbase version: 2.6.2 
- - - Meta data  - - -
phenoData
  rowNames: 1 2 ... 16 (16 total)
  varLabels: sample_name
  varMetadata: labelDescription
Loaded from:
  [1] 1.mzXML...  [16] BLANK1.mzXML
  Use 'fileNames(.)' to see all files.
protocolData: none
featureData
  featureNames: F01.S0001 F01.S0002 ... F16.S2486 (39869 total)
  fvarLabels: fileIdx spIdx ... spectrum (29 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
```

My session info is
```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] magrittr_1.5         pander_0.6.2         RColorBrewer_1.1-2   faahKO_1.20.0        xcms_3.2.0          
 [6] MSnbase_2.6.2        BiocInstaller_1.30.0 ProtGenerics_1.12.0  BiocParallel_1.14.2  mzR_2.14.0          
[11] Rcpp_0.12.18         Biobase_2.40.0       BiocGenerics_0.26.0 

loaded via a namespace (and not attached):
 [1] pillar_1.3.0           compiler_3.5.0         plyr_1.8.4             iterators_1.0.10      
 [5] tools_3.5.0            zlibbioc_1.26.0        digest_0.6.15          MALDIquant_1.18       
 [9] tibble_1.4.2           preprocessCore_1.42.0  gtable_0.2.0           lattice_0.20-35       
[13] rlang_0.2.1            Matrix_1.2-14          foreach_1.4.4          rstudioapi_0.7        
[17] S4Vectors_0.18.3       IRanges_2.14.10        multtest_2.36.0        stats4_3.5.0          
[21] grid_3.5.0             impute_1.54.0          snow_0.4-2             survival_2.42-6       
[25] XML_3.98-1.15          RANN_2.6               limma_3.36.2           ggplot2_3.0.0         
[29] splines_3.5.0          scales_1.0.0           pcaMethods_1.72.0      codetools_0.2-15      
[33] MASS_7.3-50            MassSpecWavelet_1.46.0 mzID_1.18.0            colorspace_1.3-2      
[37] affy_1.58.0            lazyeval_0.2.1         munsell_0.5.0          doParallel_1.0.11     
[41] vsn_3.48.1             crayon_1.3.4           affyio_1.50.0         
```

**Comment by jotsetung** [comment] 2018-08-16 10:41
Also, this error is most likely at a lower level. @leowkx and @haihaba, could you please run the following code to see if you get the same error (WARNING: this will take quite some time!):

```r
library(MSnbase)
library(msdata)
f <- dir(system.file("sciex/", package = "msdata"), full.names = TRUE)
for (i in 1:10000) {
    if (i %% 200 == 0)
        cat(i, "\n")
    sp <- res[[6]]
    sp <- spectrapply(res)
    sp <- spectrapply(res, FUN = mz)
    tmp <- filterRt(res, rt = c(1108, 1109))
    sp <- spectrapply(tmp)
}
```

**Comment by haihaba** [comment] 2018-08-16 16:01
I just let you know my update.
I just downgraded "Rcpp" from 0.12.18 to 0.12.17 and upgrade R-3.5.1
I submitted the same code and got the following which is better but still I got strange lines "**Error in (function (x)  : attempt to apply non-function**".

```
> xdata <- findChromPeaks(raw_data, param = cwp) 
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 22312 regions of interest ... OK: 3927 found.
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 24461 regions of interest ... OK: 6665 found.
Error in (function (x)  : attempt to apply non-function
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 25616 regions of interest ... OK: 8469 found.
Error in (function (x)  : attempt to apply non-function
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 25791 regions of interest ... OK: 8970 found.
Error in (function (x)  : attempt to apply non-function
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 25955 regions of interest ... OK: 8860 found.
Error in (function (x)  : attempt to apply non-function
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 26411 regions of interest ... OK: 8926 found.
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 26375 regions of interest ... OK: 9207 found.
Error in (function (x)  : attempt to apply non-function
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 25964 regions of interest ... OK: 9083 found.
Error in (function (x)  : attempt to apply non-function
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 26354 regions of interest ... OK: 9000 found.
Error in (function (x)  : attempt to apply non-function
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 26382 regions of interest ... OK: 9135 found.
Error in (function (x)  : attempt to apply non-function
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 26116 regions of interest ... OK: 8927 found.
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 26152 regions of interest ... OK: 9324 found.
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 26663 regions of interest ... OK: 9291 found.
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 26622 regions of interest ... OK: 9305 found.
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 26893 regions of interest ... OK: 9388 found.
Detecting mass traces at 5 ppm ... OK
Detecting chromatographic peaks in 26004 regions of interest ... OK: 9535 found.
```

@jotsetung Thank you for your comment, but I failed your code. Could you refine it? And the previous my post my output of readMSDate was "OnDiskMSnExp".

**Comment by jotsetung** [comment] 2018-08-17 03:33
Ah, sorry, the code I provided was wrong. @leowkx @haihaba, could you please try the following:
```r
library(MSnbase)
library(msdata)
f <- dir(system.file("sciex/", package = "msdata"), full.names = TRUE)
res <- readMSData(f, mode = "onDisk", verbose = FALSE)
for (i in 1:10000) {
    if (i %% 200 == 0)
        cat(i, "\n")
    sp <- res[[6]]
    sp <- spectrapply(res)
    sp <- spectrapply(res, FUN = mz)
    tmp <- filterRt(res, rt = c(1108, 1109))
    sp <- spectrapply(tmp)
}
```

@haibaba, thanks for the feedback. And the `xdata` object, is that an `XCMSnExp` object? If yes, you could ignore the error messages. They are disturbing but should not affect the peak detection - still, I would like to (try again to) find a way to fix them - but for that I need to be able to reproduce them. So far I did not get them on macOS and also not on my Windows and Linux test machines.

**Comment by haihaba** [comment] 2018-08-21 17:02
@jotsetung Thank you for reply. My `xdata` object is `XCMSnExp`. And my system is Windows Server 2016.

**Comment by jotsetung** [comment] 2018-08-22 11:04
Since you have an `XCMSnExp` the analysis ran through. As mentioned above it *should* be OK to ignore the error. To validate, you could save the `XCMSnExp` object you got from your analysis showing the error, re-run the analysis and (if the second time you did not get these errors) compare the two objects with something like:

```r
library(testthat)
expect_equal(chromPeaks(res), chromPeaks(res_new))
```

An update: I did run peak detection on sets of 6 files repeatedly (500 times) on Windows (7), linux and macOS and did not see this error. So, at present I struggle to replicate the error which is necessary to find a solution to fix it. I will keep on testing with different files.

**Comment by jotsetung** [comment] 2018-11-22 14:16
Closing this issue as I don't see a fix for this problem. The errors should not influence the data processing/results.

**Closed by jotsetung** 2018-11-22 14:16 UTC
