### ISSUE TITLE
Inf values in featureValues

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#323] opened 2018-10-25 07:30 UTC
Hi, @MarrSue and I are currently debugging an issue where have an `XCMSnExp` with one(!) feature 
that has 1) few real intensity values, 2) `NA`s and 3) `Inf` values. `Inf` should not happen. Yours, Steffen
```
dataMatrix <- featureValues(xdata, method="medret", value="into")
dataMatrix[which(apply(dataMatrix, MARGIN=1, function(x) any(is.infinite(x)))), ]
```

**Comment by sneumann** [comment] 2018-10-25 12:51
Yup. Caveat: I corrected the initial report, fillPeaks *was* done. And the `Inf`s came in through `fillChromPeaks`:

if I extract the chromPeaks() by index from the one feature row that has `Inf` here, 
then the `Inf` are exactly those samples that were filled-in, `mzmax-mzmin=0.028` and `rtmax-rtmin=0.365`

`chromPeaks(xdata)[dataMatrixIndex[which(apply(dataMatrixInto, MARGIN=1, function(x) any(is.infinite(x)))), ], ]`

Not exactly sure which xcms version is used on W4M, need to ask @lecorguille for that.
Yours, Steffen

![image](https://user-images.githubusercontent.com/195385/47500632-96503180-d863-11e8-9cf1-3bcc85f3f489.png)

```
MSn experiment data ("XCMSnExp")
Object size in memory: 25.01 Mb
- - - Spectra data - - -
 MS level(s): 1 
 Number of spectra: 114382 
 MSn retention times: -1:59 - 20:3 minutes
- - - Processing information - - -
Concatenated [Tue Oct 23 11:58:46 2018] 
 MSnbase version: 2.4.0 
- - - Meta data  - - -
phenoData
  rowNames: ./pos_030_2017_C_PLALAN_C115_a_1-E,2_01_8316.mzML
    ./pos_QC2017AtoD_1-A,3_01_9030.mzML ...
    ./pos_QC2017AtoD_1-A,3_01_8333.mzML (32 total)
  varLabels: sample_name sample_group
  varMetadata: labelDescription
Loaded from:
  [1] pos_030_2017_C_PLALAN_C115_a_1-E,2_01_8316.mzML...  [32] pos_QC2017AtoD_1-A,3_01_8333.mzML
  Use 'fileNames(.)' to see all files.
protocolData: none
featureData
  featureNames: F1.S0001 F1.S0002 ... F32.S3575 (114382 total)
  fvarLabels: fileIdx spIdx ... spectrum (28 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
- - - xcms preprocessing - - -
Chromatographic peak detection:
 method: centWave 
 355790 peaks identified in 32 samples.
 On average 11118 chromatographic peaks per sample.
Alignment/retention time adjustment:
 method: peak groups 
Correspondence:
 method: chromatographic peak density 
 9591 features identified.
 Median mz range of features: 0.0030608
 Median rt range of features: 1.1375
 187669 filled peaks (on average 5864.656 per sample).
```

**Comment by jotsetung** [comment] 2018-10-25 13:04
Strange. I thought we added the `max(1, ...)` in the `.getChromPeakData` function to explicitly avoid `Inf` values (https://github.com/sneumann/xcms/blob/master/R/functions-XCMSnExp.R#L364:L372 ). Can you reproduce the error with the current version (3.3.4?).

**Comment by jotsetung** [comment] 2018-10-25 13:07
If this error still persists in the newest version we could ask for `is.finite` on the integrated signal and only fill it if that's the case. As you say @sneumann, would be good to know which xcms version produced this `Inf`.

**Comment by jotsetung** [comment] 2018-10-25 13:11
Just checked. This was fixed in `xcms` version 3.3.1. So, the *official* one from Bioconductor 3.7 (xcms 3.2.0) does not have the fix yet.

**Closed** 2018-10-30 06:29 UTC

**Comment by lecorguille** [comment] 2018-12-04 09:34
@jotsetung Can you point me the patch which fix this?
That way, I will include the necessary functions in my code in the meanwhile bioconductor 3.8 support in BioConda.

**Comment by stanstrup** [comment] 2018-12-04 09:40
You need to install from github:

```r
devtools::install_github("lgatto/MSnbase", INSTALL_opts =  "--no-multiarch")
devtools::install_github("sneumann/xcms", INSTALL_opts =  "--no-multiarch")
```

**Comment by jotsetung** [comment] 2018-12-05 18:08
That is a tricky question @lecorguille as I can't recall when exactly I fixed this. You should be able to fix with the `.getChromPeakData` from the current master branch: https://github.com/sneumann/xcms/blob/master/R/functions-XCMSnExp.R#L319-L389 

In particular, it's the `max(1` in https://github.com/sneumann/xcms/blob/master/R/functions-XCMSnExp.R#L372 that fixes the problem. Hope this helps.

**Comment by lecorguille** [comment] 2019-01-09 09:18
@jotsetung I ship the new version of your function `.getChromPeakData` in my [lib.r](https://github.com/workflow4metabolomics/xcms/blob/dev/tools/scripts/lib-xcms3.x.x.r#L156)

I tested using the useful `message("Requesting YYOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO", nrow(res), " peaks from ",              basename(fileNames(object)), " ... ", appendLF = FALSE)`

But this function isn't seen but the main process. I also tried without the `.` but it's the same.

(RRrrr, I should follow some training session around R :/)

**Comment by jotsetung** [comment] 2019-01-09 10:19
Yes, right. Package functions search for other functions first in their own namespace. That's the reason why the *original* function is always used. A solution would be if you ship also the `fillChromPeaks` method with your script (https://github.com/sneumann/xcms/blob/master/R/methods-XCMSnExp.R#L2623-L2806).

You'll however have to add a `xcms:::` before calls to package-internal functions: `.hasFilledPeaks`, `.param2string`, `.getMSWPeakData`, `.getChromPeakData_matchedFilter`, `.copy_env`, `addProcessHistory`. e.g. replace `.hasFilledPeaks` with `xcms:::.hasFilledPeaks`.

**Comment by lecorguille** [comment] 2019-01-11 10:32
Damn! Not so easy :/

```
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :
object 'fixedMz' not found
Calls: fillChromPeaks -> ::: -> get
```

If I add stupidly this : https://github.com/sneumann/xcms/blob/f887c534ba5e9ad81d90b63b6d1103704a8a9ef8/R/functions-Params.R#L326-L330

```
Error in fixedMz(param) :
No slot of name "fixedMz" for this object of class "FillChromPeaksParam"
Calls: fillChromPeaks -> fixedMz
```

If I add even more stupidly this: https://github.com/sneumann/xcms/blob/f887c534ba5e9ad81d90b63b6d1103704a8a9ef8/R/functions-Params.R#L320-L324

```
Error in .nextMethod(.Object, ...) :
invalid names for slots of class "FillChromPeaksParam": fixedMz, fixedRt
Calls: %in% ... .local -> callNextMethod -> eval -> eval -> .nextMethod
```

Hum! I'm dry of stupid idea!

**Comment by lecorguille** [comment] 2019-01-11 10:43
But but, good news. I have just discover that I can target new versions of the package during the migration to R 3.5.1 (gcc7) using the specific sub channel `bioconda/label/gcc7` 👍 
It lets us drift to xcms 3.4.2

```
conda search -c bioconda/label/gcc7 bioconductor-xcms
Loading channels: done
# Name                  Version           Build  Channel
bioconductor-xcms          1.44.0               0  bioconda
bioconductor-xcms          1.46.0               0  bioconda
bioconductor-xcms          1.52.0        r3.4.1_0  bioconda
bioconductor-xcms          1.52.0  r341h470a237_1  bioconda
bioconductor-xcms           3.0.0        r3.4.1_0  bioconda
bioconductor-xcms           3.0.0          r341_1  bioconda
bioconductor-xcms           3.4.1  r351h0a44026_0  bioconda/label/gcc7
bioconductor-xcms           3.4.2  r351h0a44026_0  bioconda/label/gcc
```

**Comment by jotsetung** [comment] 2019-01-11 11:03
Uh, yes, right, sorry, there are more things that changed. But the possibility to use the updated `xcms` is really a game changer! This means no more hacks!

**Comment by lecorguille** [comment] 2019-02-01 13:55
# Issue
Ok! I found enough time to have a look at this error message with `fillChromPeaks`

```R
> xdata <- fillChromPeaks(xdata)
Defining peak areas for filling-in .... OK
Start integrating peak areas from original files
Requesting 4252 missing peaks from ko15.CDF ... got 1558.
Requesting 4140 missing peaks from ko16.CDF ... got 1435.
Requesting 4251 missing peaks from wt15.CDF ... got 1436.
Requesting 4218 missing peaks from wt16.CDF ... got 1538.
Error in sprintf(paste0("CP", "%0", ceiling(log10(toId + 1L)), "d"), (maxId +  :
  negative length vectors are not allowed
In addition: Warning messages:
1: In max(as.numeric(sub("^CP", "", rownames(chromPeaks(object))))) :
  no non-missing arguments to max; returning -Inf
2: In paste0("CP", "%0", ceiling(log10(toId + 1L)), "d") : NaNs produced
```

I suspect a problem of retrocompatibility

# The test script
```
library(xcms)
cdfs <- dir(system.file("cdf", package = "faahKO"), full.names = TRUE,
        recursive = TRUE)
cdfs <- cdfs[c(1,2,7,8)]
pd <- data.frame(
        sample_name = sub(basename(cdfs), pattern = ".CDF",
        replacement = "", fixed = TRUE),
        sample_group = c(rep("KO", 2), rep("WT", 2)),
        stringsAsFactors = FALSE)
raw_data <- readMSData(files = cdfs, pdata = new("NAnnotatedDataFrame", pd),
        mode = "onDisk")
cwp <- CentWaveParam()
xdata <- findChromPeaks(raw_data, param = cwp)
```

## xcms_3.4.2
```R
> head(rownames(chromPeaks(xdata)))
[1] "CP0001" "CP0002" "CP0003" "CP0004" "CP0005" "CP0006"
```

## xcms_3.0.0
```R
> head(rownames(chromPeaks(xdata)))
NULL
```

# Start of explanation of my error message
I used to launch tool individually for my functional test. No problemo until `fillChromPeaks`.
But when I fed the fillChromPeaks.3.4.2 with an output from groupChromPeaks.3.0.0, it fails.
