### ISSUE TITLE
issue with plot Chromatograms object, xcms 3.9.1

### ISSUE THREAD

**Issue by MetabolomicsSA** [sneumann/xcms#479] opened 2020-05-20 02:30 UTC
Hi crew,
I am experiencing an error with the xcms 39.1 when plotting a Chromatogram object.
The error appears when I run the example provided in the package documentation using the following code: 
    library(xcms)
    library(faahKO)
    faahko_files <- c(system.file('cdf/KO/ko15.CDF', package = "faahKO"), 
    system.file('cdf/KO/ko18.CDF', package = "faahKO"))
    od <- readMSData(faahko_files, mode = "onDisk")
    od <- filterRt(od, rt = c(2500, 3000))
    xod <- findChromPeaks(od, param = CentWaveParam(prefilter = c(3, 20000)))
    mzr <- matrix(c(335, 335, 344, 344), ncol = 2, byrow = TRUE)
    rtr <- matrix(c(2700, 2900, 2600, 2750), ncol = 2, byrow = TRUE)
    chrs <- chromatogram(xod, mz = mzr, rt = rtr)
    plot(chrs)

   **Error in (function (cl, name, valueClass)  : 
  ‘.processHistory’ is not a slot in class “list”**

I have a similar error when i try the same plot  function on my data files 

     **Error in (function (cl, name, valueClass)  : 
      ‘featureDefinitions’ is not a slot in class “list”**

The function works when tested using R 3.6.2 and xcms 3.8.1

Any help in fixing this would be much appreciated ,

thanks!

sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] faahKO_1.28.0       xcms_3.9.1          MSnbase_2.14.1     
 [4] ProtGenerics_1.20.0 S4Vectors_0.26.1    mzR_2.22.0         
 [7] Rcpp_1.0.4.6        BiocParallel_1.22.0 Biobase_2.48.0     
[10] BiocGenerics_0.34.0

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.0       purrr_0.3.4            splines_4.0.0         
 [4] lattice_0.20-41        colorspace_1.4-1       vctrs_0.3.0           
 [7] snow_0.4-3             vsn_3.56.0             XML_3.99-0.3          
[10] survival_3.1-12        rlang_0.4.6            pillar_1.4.4          
[13] glue_1.4.1             affy_1.66.0            RColorBrewer_1.1-2    
[16] affyio_1.58.0          foreach_1.5.0          lifecycle_0.2.0       
[19] plyr_1.8.6             mzID_1.26.0            robustbase_0.93-6     
[22] zlibbioc_1.34.0        munsell_0.5.0          pcaMethods_1.80.0     
[25] gtable_0.3.0           codetools_0.2-16       IRanges_2.22.1        
[28] doParallel_1.0.15      MassSpecWavelet_1.54.0 preprocessCore_1.50.0 
[31] DEoptimR_1.0-8         scales_1.1.1           BiocManager_1.30.10   
[34] limma_3.44.1           RANN_2.6.1             impute_1.62.0         
[37] ggplot2_3.3.0          digest_0.6.25          dplyr_0.8.5           
[40] ncdf4_1.17             grid_4.0.0             magrittr_1.5          
[43] tibble_3.0.1           crayon_1.3.4           pkgconfig_2.0.3       
[46] MASS_7.3-51.5          ellipsis_0.3.1         Matrix_1.2-18         
[49] assertthat_0.2.1       iterators_1.0.12       R6_2.4.1              
[52] MALDIquant_1.19.3      multtest_2.44.0        compiler_4.0.0

**Comment by jorainer** [comment] 2020-05-20 07:55
The error message is very strange and I can not reproduce on my setting.

Could you please run `BiocManager::install()` in your R? That should ideally update all packages to the current Bioconductor release (11) and please try the code after that again.

**Comment by MetabolomicsSA** [comment] 2020-05-20 23:34
That solved the problem! Thank you very much!

**Comment by jorainer** [comment] 2020-05-22 06:12
I'm closing the issue now - feel free to reopen if needed.

**Comment by MetabolomicsSA** [comment] 2020-09-15 04:01
I'm reopening this issue to provide more info.
The error seems to pop up when installing xcms after a recent update (13th of September in this case) even after updating BiocManager . 
Also, the error only occurs when installing from Binaries.  When the package is installed from source everything runs fine.
Hope this is useful.
thanks

**Comment by jorainer** [comment] 2020-09-16 06:32
How are you installing `xcms`? What sometimes happens that the binary version of a package update is not created (e.g. if there is a timeout) and hence the source version is more up-to-date than the binary version. The generation of the binary version is unfortunately out of our control.

Could you please provide the sessionInfo for the installation where it fails and the sessionInfo for the installation that works?

**Comment by MetabolomicsSA** [comment] 2020-09-17 02:27
thank you very much for getting back to me .
I usually install xcms either using   'BiocManager::install('xcms') ' or via GitHub using devtools.

###  installation that works (source) 

sessionInfo () 

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] xcms_3.10.1         MSnbase_2.14.2      ProtGenerics_1.20.0
[4] S4Vectors_0.26.1    mzR_2.22.0          Rcpp_1.0.5         
[7] BiocParallel_1.22.0 Biobase_2.48.0      BiocGenerics_0.34.0

loaded via a namespace (and not attached):
 [1] SummarizedExperiment_1.18.2 tidyselect_1.1.0           
 [3] purrr_0.3.4                 lattice_0.20-41            
 [5] colorspace_1.4-1            vctrs_0.3.4                
 [7] generics_0.0.2              vsn_3.56.0                 
 [9] XML_3.99-0.5                rlang_0.4.7                
[11] pillar_1.4.6                glue_1.4.2                 
[13] affy_1.66.0                 RColorBrewer_1.1-2         
[15] matrixStats_0.56.0          affyio_1.58.0              
[17] GenomeInfoDbData_1.2.3      foreach_1.5.0              
[19] lifecycle_0.2.0             plyr_1.8.6                 
[21] mzID_1.26.0                 robustbase_0.93-6          
[23] zlibbioc_1.34.0             munsell_0.5.0              
[25] pcaMethods_1.80.0           gtable_0.3.0               
[27] codetools_0.2-16            IRanges_2.22.2             
[29] doParallel_1.0.15           GenomeInfoDb_1.24.2        
[31] MassSpecWavelet_1.54.0      preprocessCore_1.50.0      
[33] DEoptimR_1.0-8              scales_1.1.1               
[35] BiocManager_1.30.10         limma_3.44.3               
[37] DelayedArray_0.14.1         XVector_0.28.0             
[39] RANN_2.6.1                  impute_1.62.0              
[41] ggplot2_3.3.2               digest_0.6.25              
[43] dplyr_1.0.2                 ncdf4_1.17                 
[45] GenomicRanges_1.40.0        grid_4.0.2                 
[47] tools_4.0.2                 bitops_1.0-6               
[49] magrittr_1.5                RCurl_1.98-1.2             
[51] tibble_3.0.3                crayon_1.3.4               
[53] pkgconfig_2.0.3             Matrix_1.2-18              
[55] MASS_7.3-53                 ellipsis_0.3.1             
[57] iterators_1.0.12            R6_2.4.1                   
[59] MALDIquant_1.19.3           compiler_4.0.2

**Comment by MetabolomicsSA** [comment] 2020-09-17 02:28
**installation that doesn' t work** (binaries)

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] xcms_3.9.1          MSnbase_2.14.2      ProtGenerics_1.20.0
[4] S4Vectors_0.26.1    mzR_2.22.0          Rcpp_1.0.5         
[7] BiocParallel_1.22.0 Biobase_2.48.0      BiocGenerics_0.34.0

loaded via a namespace (and not attached):
 [1] RColorBrewer_1.1-2     DEoptimR_1.0-8         compiler_4.0.2        
 [4] pillar_1.4.6           BiocManager_1.30.10    plyr_1.8.6            
 [7] iterators_1.0.12       zlibbioc_1.34.0        tools_4.0.2           
[10] digest_0.6.25          ncdf4_1.17             MALDIquant_1.19.3     
[13] lifecycle_0.2.0        tibble_3.0.3           preprocessCore_1.50.0 
[16] gtable_0.3.0           lattice_0.20-41        pkgconfig_2.0.3       
[19] rlang_0.4.7            Matrix_1.2-18          foreach_1.5.0         
[22] dplyr_1.0.2            IRanges_2.22.2         generics_0.0.2        
[25] vctrs_0.3.4            multtest_2.44.0        grid_4.0.2            
[28] tidyselect_1.1.0       robustbase_0.93-6      glue_1.4.2            
[31] impute_1.62.0          R6_2.4.1               survival_3.2-3        
[34] XML_3.99-0.5           RANN_2.6.1             limma_3.44.3          
[37] ggplot2_3.3.2          purrr_0.3.4            magrittr_1.5          
[40] splines_4.0.2          scales_1.1.1           pcaMethods_1.80.0     
[43] codetools_0.2-16       ellipsis_0.3.1         MASS_7.3-53           
[46] MassSpecWavelet_1.54.0 mzID_1.26.0            colorspace_1.4-1      
[49] affy_1.66.0            doParallel_1.0.15      munsell_0.5.0         
[52] vsn_3.56.0             crayon_1.3.4           affyio_1.58.0

**Comment by jorainer** [comment] 2020-09-17 05:52
OK, I see where the problem is. With source installation you get `xcms` version 3.10.1 while with binary you get only 3.9. and in fact that's the problem. There's a build timeout on the Bioconductor for `xcms` version 3.10.1 on the build machines and that's why there is no binary version available (yet) for that package. I will try to get around that build timeout.

thanks for reporting!

**Comment by MetabolomicsSA** [comment] 2020-09-17 06:16
Thank you very much for your help Johannes!

I’m glad it was useful ,

Luca

**Comment by jorainer** [comment] 2020-10-21 06:07
Closing the issue now. Feel free to re-open if needed.

**Closed by jorainer** 2020-10-21 06:07 UTC
