### ISSUE TITLE
Error with findChromPeaks

### ISSUE THREAD

**Issue by tuhulab** [sneumann/xcms#361] opened 2019-03-20 14:39 UTC
Dear Sir or Madam,

It's my first time to submit an issue in GitHub. Please let me know if I need to provide more information.

I encounted an error when I use 'findChromPeaks' errors. 

I first get my raw data like this:
`  raw_data <- readMSData(files = pos_path, mode = "onDisk",msLevel. = 1, centroided. = TRUE)`
Second, I define my Centwave parameters:
`cwp <- CentWaveParam(ppm=30,
                     peakwidth= c(2,20),
                     snthresh=4,
                     prefilter=c(2,15),
                     mzdiff=-0.001,
                     integrate = 1,
                     noise=15,mzCenterFun = 'mean')`
In the end, I run the findChromPeaks function like this:
`xdata <- findChromPeaks(raw_data, param = cwp)`

It gave the error message:
`Error in quantile.default(pk[, 2], qtl) : 
 missing values and NaN's not allowed if 'na.rm' is FALSE
`

However, the  error did not appear when I tested with my colleague's data. Also, I noticed that this error only occured to part of my data.
For example, when I do this (take only one sample):
`> raw_data <- readMSData(files = pos_path[4], mode = "onDisk",msLevel. = 1, centroided. = TRUE)
xdata <- findChromPeaks(raw_data, param = cwp)`

No error appears. 'xdata' was successfully generated.

`Detecting mass traces at 40 ppm ... OK
Detecting chromatographic peaks in 3417 regions of interest ... OK: 2341 found.`

However, the error happened when I change '4' to '2' or some of other numbers.
`> raw_data <- readMSData(files = pos_path[2], mode = "onDisk",msLevel. = 1, centroided. = TRUE)
xdata <- findChromPeaks(raw_data, param = cwp)`

I don't know whether it's the same reason with this issus although they're different functions. [https://github.com/sneumann/xcms/issues/249](url)

Looking forward to hearing from you.

Additional info:
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] RColorBrewer_1.1-2  readxl_1.3.0        xcms_3.4.4          BiocParallel_1.16.2
 [5] forcats_0.4.0       stringr_1.4.0       dplyr_0.8.0.1       purrr_0.3.1        
 [9] readr_1.3.1         tidyr_0.8.3         tibble_2.0.1        ggplot2_3.1.0      
[13] tidyverse_1.2.1     MSnbase_2.8.3       ProtGenerics_1.14.0 S4Vectors_0.20.1   
[17] mzR_2.16.2          Rcpp_1.0.0          Biobase_2.42.0      BiocGenerics_0.28.0

loaded via a namespace (and not attached):
 [1] httr_1.4.0             vsn_3.50.0             jsonlite_1.6          
 [4] splines_3.5.2          foreach_1.4.4          modelr_0.1.4          
 [7] assertthat_0.2.0       BiocManager_1.30.4     affy_1.60.0           
[10] cellranger_1.1.0       yaml_2.2.0             robustbase_0.93-3     
[13] impute_1.56.0          pillar_1.3.1           backports_1.1.3       
[16] lattice_0.20-38        glue_1.3.0             limma_3.38.3          
[19] digest_0.6.18          rvest_0.3.2            colorspace_1.4-0      
[22] Matrix_1.2-15          preprocessCore_1.44.0  plyr_1.8.4            
[25] MALDIquant_1.18        XML_3.98-1.18          pkgconfig_2.0.2       
[28] broom_0.5.1            haven_2.1.0            zlibbioc_1.28.0       
[31] scales_1.0.0           RANN_2.6.1             affyio_1.52.0         
[34] generics_0.0.2         IRanges_2.16.0         withr_2.1.2           
[37] lazyeval_0.2.1         MassSpecWavelet_1.48.1 cli_1.0.1             
[40] survival_2.43-3        magrittr_1.5           crayon_1.3.4          
[43] ncdf4_1.16             doParallel_1.0.14      nlme_3.1-137          
[46] MASS_7.3-51.1          xml2_1.2.0             tools_3.5.2           
[49] hms_0.4.2              munsell_0.5.0          pcaMethods_1.74.0     
[52] compiler_3.5.2         mzID_1.20.1            rlang_0.3.1           
[55] grid_3.5.2             iterators_1.0.10       rstudioapi_0.9.0      
[58] gtable_0.2.0           codetools_0.2-15       multtest_2.38.0       
[61] R6_2.4.0               lubridate_1.7.4        stringi_1.3.1         
[64] DEoptimR_1.0-8         tidyselect_0.2.5
>

**Comment by tentrillion** [comment] 2019-03-21 16:28
What type of data do you have?  `*.mzML`, or `*.netCDF`, or something else?  Does `pos_path[2]` contain a different data type than `pos_path[4]`?  Or are some of the data centroided and some not?

**Comment by tuhulab** [comment] 2019-03-25 07:12
Hi, @tentrillion thanks for your reply.
I have `.cdf` data. They were converted from waters `.raw` data by DataBridge (provided by waters).
`pos_path[2]` and `pos_path[4]` have same type. Both were centroid and acquired by the same instrument and same parameters.
Do you have more suggestions for me to check with my raw data?
Wish you have a nice day!
Sincerely, Tu

**Comment by jotsetung** [comment] 2019-03-25 11:13
Can you please check if the following throws an error:
```r
isCentroided(raw_data[[1]])
```

**Comment by tuhulab** [comment] 2019-03-25 17:12
Dear @jotsetung,
Thanks for your reply. 
It returned 
`25% 
NA`

**Comment by jotsetung** [comment] 2019-03-28 08:43
Hm, can you please have a look at the intensities of this first spectrum you have?
```r
sp <- raw_data[[1]]
intensity(sp)
```

**Comment by tuhulab** [comment] 2019-03-28 14:07
Hi, @jotsetung 
Thank you very much for your reply.
It returns result as following:
`[1] 1.012658 1.012658 1.012658 1.012658 1.012658 1.012658 1.012658 1.012658 1.012658`

**Comment by jotsetung** [comment] 2019-03-29 11:45
This is puzzling. All intensities are the same?

**Comment by tuhulab** [comment] 2019-03-29 12:28
@jotsetung 
Not really. When I check some other data: `sp <- raw_data[[232]]
> intensity(sp)
   [1]   1.012658   1.012658   1.012658   1.012658   7.088608   1.012658   1.012658
   [8]   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
  [15]   1.012658  10.126579   1.012658   1.012658   1.012658   1.012658   1.012658
  [22]   1.012658   3.037975   1.012658   1.012658   1.012658   1.012658   1.012658
  [29]   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
  [36]   1.012658   1.012658   1.012658   4.050632   2.025316   2.025316   1.012658
  [43]  10.126579   6.075951   1.012658   1.012658   1.012658   1.012658   6.075951
  [50] 143.066528   2.025316   1.012658   1.012658   1.012658   1.012658   2.025316
  [57]   3.037975   3.037975   1.012658   1.012658   1.012658   1.012658   1.012658
  [64]   2.025316   1.012658   1.012658   1.012658   3.037975   1.012658   8.006477
  [71]   1.012658   2.025316   1.012658   1.012658   1.012658   1.012658   4.050632
  [78]   1.012658   1.012658   1.012658   1.012658   2.025316   1.012658   2.025316
  [85]   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
  [92]   1.012658   1.012658   1.012658   1.012658   1.012658   2.025316   1.012658
  [99]   1.012658   1.012658   1.012658   2.025316   1.012658   1.012658   2.025316
 [106]   1.012658   2.025316   1.012658   1.012658   1.012658   1.012658   2.025316
 [113]   1.012658   1.012658   1.012658   1.012658  10.126579   1.012658   6.841499
 [120]   1.012658   1.012658  18.227844   1.012658   1.012658   1.012658   1.012658
 [127]   2.025316   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
 [134]   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
 [141]   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
 [148]   1.012658   1.012658   1.012658   1.012658   2.025316   4.050632   1.012658
 [155]   3.037975   1.012658   1.012658   2.025316  21.265823   1.012658   1.012658
 [162]   1.012658   5.783039   6.075951   2.025316   1.012658   1.012658   4.050632
 [169]   1.012658   2.025316 174.917114   1.012658   1.012658   1.012658   1.012658
 [176]   2.025316   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
 [183]   1.012658   3.037975   1.012658   2.025316   1.012658   2.025316  12.151901
 [190]   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
 [197]   1.012658   1.012658   1.012658   4.467888   1.012658   1.012658   1.012658
 [204]   1.012658   1.012658   1.012658   1.012658   5.063290   1.012658   1.012658
 [211]   1.012658   4.050632   1.012658   1.012658   1.012658   1.012658   1.012658
 [218]   1.012658   1.012658   7.674400   3.464840   3.037975   1.012658   1.012658
 [225]   1.012658   1.012658   1.012658   1.012658   2.025316   1.012658   1.012658
 [232]   1.012658   1.012658   2.025316   1.012658   1.012658   3.037975   5.063290
 [239]   1.012658   1.012658   1.012658  11.972824   1.012658   2.025316   1.012658
 [246]   1.012658   2.025316   2.025316   1.012658   3.037975   9.113922   1.012658
 [253]   1.012658   1.012658   1.012658  14.177216   1.012658   1.012658   1.012658
 [260]   1.012658   1.012658   1.012658   1.012658   1.012658   6.075951   1.012658
 [267]   1.012658   1.012658   1.012658   2.025316   2.025316   1.505631   1.012658
 [274]  68.776489   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
 [281]   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658  11.577499
 [288]   2.025316   1.012658   1.012658   1.012658   1.012658   1.012658   2.025316
 [295]   1.012658   1.012658   1.012658   1.012658   1.012658   2.025316   1.012658
 [302]   2.025316   1.012658   7.578388   6.075951   1.012658   1.012658   1.012658
 [309]   1.012658   7.084690   4.044106   2.022705   2.025316   1.012658   1.012658
 [316]   1.012658   1.012658   2.025316   2.025316   7.082081   4.530807   1.012658
 [323]   1.012658   1.012658   1.012658   2.025316  17.209961   1.012658   1.012658
 [330]   1.012658   1.012658   2.025316   6.075951   3.037975   1.012658   1.012658
 [337]   1.012658   1.012658   1.012658   3.037975   1.012658   2.025316   1.012658
 [344]   1.012658   6.075951   1.012658   4.050632   1.012658   1.012658   1.012658
 [351]   1.012658   5.063290   3.037975   1.012658   1.012658   7.088608   1.012658
 [358]   1.012658   1.012658   1.012658  32.405060   2.025316   1.012658   1.012658
 [365]   1.012658   1.012658   1.012658   1.012658   3.037975   3.037975   2.025316
 [372]   1.012658   1.012658   2.025316   2.025316   2.025316   1.012658   2.025316
 [379]   1.012658   1.012658   4.050632   1.012658   3.037975   1.012658   1.012658
 [386]   1.012658   3.579172   5.063290   1.012658   1.012658   2.025316   1.012658
 [393]   1.012658   1.012658   1.012658   2.025316   1.012658   1.012658   2.025316
 [400]   5.063290   3.037975   1.012658   1.012658   8.695892   7.088608   1.012658
 [407]   1.012658   1.012658   1.012658   3.037975   1.012658   1.012658   1.012658
 [414]   1.012658   2.025316   1.012658   1.012658   3.037975  14.842484   1.012658
 [421]   1.012658   1.012658   3.037975   1.012658   1.012658   1.012658   1.012658
 [428]   4.050632   1.012658   1.012658   1.012658   1.012658   4.050632   1.012658
 [435]   1.012658   1.012658   2.025316   4.050632   7.088608   1.012658   1.012658
 [442]   1.012658   1.012658   1.012658   1.012658   3.037975   9.113922   1.012658
 [449]   1.012658   1.012658   3.037975   1.012658   1.012658   2.025316   1.012658
 [456]   1.012658   1.012658   1.012658   1.012658   5.063290   6.075951   1.012658
 [463]   1.012658   5.063290   4.050632   1.012658   1.012658   1.012658   2.025316
 [470]   1.012658   1.012658   1.012658  18.227844  31.920853   1.012658   1.012658
 [477]   1.012658   2.025316  24.303802   5.063290   1.012658   1.012658   1.012658
 [484]   1.012658   1.012658   1.012658   1.012658   2.025316  39.530548  92.449646
 [491]   1.012658   2.025316   1.012658   3.037975   2.025316   1.012658   2.025316
 [498]   2.025316   5.254932   8.922287   1.012658   1.012658   1.012658   1.012658
 [505]   2.025316   1.012658   1.012658   2.025316   1.012658   2.025316   7.088608
 [512]   2.025316   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
 [519]   9.589500   2.025316   1.012658   1.012658   1.012658   5.063290   4.666916
 [526]   3.037975   1.012658   1.012658   1.012658   1.012658   2.025316   1.012658
 [533]   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658   2.025316
 [540]   1.012658   1.012658   2.025316   1.012658   1.012658   1.012658   1.012658
 [547]   1.012658   1.012658   7.088608   1.012658   1.012658   1.012658  14.109489
 [554]   1.012658   1.012658   1.012658   1.012658   3.037975   1.012658   1.012658
 [561]   1.012658   1.012658   4.050632   3.037975   1.012658   1.012658   2.025316
 [568]   1.012658  27.432785   2.025316   1.012658   1.012658   3.037975   1.012658
 [575]   1.012658  16.202530   3.370955   1.012658   1.012658   1.012658   1.012658
 [582]   1.012658   1.012658   2.025316   1.012658   1.012658   1.012658   1.012658
 [589]   1.012658   2.025316   1.012658   1.012658   3.037975   1.012658   4.050632
 [596]   3.037975   1.012658   1.012658   1.012658   5.063290   2.025316   1.012658
 [603]   1.012658   1.012658   4.050632   1.012658   2.025316   6.967503   1.012658
 [610]   1.012658   1.012658   1.012658   1.012658   6.619579   2.630651   1.012658
 [617]   1.012658   1.012658   1.012658   3.037975   3.070835   1.012658   1.012658
 [624]   1.012658   2.025316   4.050632   1.012658   1.012658   1.012658   1.617994
 [631]   1.889543   3.037975   1.012658   1.012658   2.025316   1.821655  18.833191
 [638]   1.012658   1.012658   1.012658   1.012658   7.757462  76.203552   1.012658
 [645]   1.012658   1.012658   1.012658   1.012658   2.025316   4.948689   1.012658
 [652]   1.012658   1.012658   2.025316   1.012658  10.731918   7.965492   1.012658
 [659]   1.012658   1.012658   1.012658   1.012658   1.012658   1.452311   2.440552
 [666]   4.050632   1.012658   1.012658   1.012658   1.012658   2.025316   4.768795
 [673]   3.037975   1.012658   1.012658   1.012658   1.012658   1.889543  10.126579
 [680]   2.025316   1.012658   1.012658   7.413658   1.012658   1.012658   1.012658
 [687]   1.012658   3.340788   2.025316   1.012658   1.012658   1.012658   1.012658
 [694]   1.012658   3.802382   2.417347   1.012658   1.012658   9.763893   1.012658
 [701]   1.012658   1.012658   2.025316   3.037975   5.617546   5.063290   1.012658
 [708]   1.012658   1.012658   2.025316   3.037975   2.025316   3.037975   1.012658
 [715]   2.541473   3.926508   1.012658   3.037975   1.012658   1.012658   2.808773
 [722]  11.139236   2.025316   2.293222   1.012658   1.012658   1.012658   1.012658
 [729]   2.025316  22.786301   2.665598   2.025316   1.012658   2.025316   2.789724
 [736]   3.926508   1.012658   1.012658   1.012658   2.025316   1.012658   2.768232
 [743]   1.012658   3.037975   1.012658   1.012658   2.025316   1.687098   1.012658
 [750]   2.361538   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
 [757]   1.012658   1.012658 126.160889   1.012658   1.012658   3.037975  12.328529
 [764]   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
 [771]   4.773853   1.012658   1.012658   1.012658   1.513507   1.012658   1.012658
 [778]   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
 [785]   3.035976  37.508881   1.012658   1.012658   2.025316   3.037975   2.025316
 [792]   5.453812  32.101807   1.012658   1.012658   1.012658   1.012658   1.012658
 [799]   5.246700   6.840054   2.594803   8.544441   1.012658   1.012658   1.012658
 [806]   2.025316   1.012658   2.025316   4.816517  23.629440 640.424805   6.075951
 [813]   1.012658   2.025316   3.037975   1.012658   1.012658   5.603687   6.075951
 [820]  12.630501  87.205383   3.276855   3.037975   3.037975   2.025316   4.050632
 [827]   5.063290   7.088608   2.025316   4.050632   3.037975   2.025316   7.088608
 [834] 103.844116  14.177216   3.037975   3.037975   2.025316   1.012658   1.012658
 [841]   4.050632   2.025316   2.025316   2.025316   2.692581   2.025316   1.012658
 [848]   3.037975  12.244896   3.037975   2.025316   1.012658   1.012658   1.012658
 [855]   3.037975   3.037975   3.037975   2.025316   1.012658   2.025316   3.037975
 [862]   1.890445   2.633360   1.012658   2.025316   2.025316   1.012658   1.012658
 [869]   2.025316   1.012658   1.012658   2.768232   2.633360   2.025316   1.012658
 [876]   1.012658   3.037975   1.012658   2.025316   1.012658   1.012658   1.012658
 [883]   3.037975  13.091019   1.890445   2.025316   1.012658   1.012658   1.012658
 [890]   1.289588   1.012658   1.012658   1.012658   2.025316   1.012658   4.050632
 [897]   3.037975   1.657453   1.012658   1.012658   1.012658   1.012658   3.037975
 [904]   2.025316   4.673191   1.012658   1.012658   1.012658   1.012658   2.025316
 [911]   4.050632 183.116577   1.012658   2.025316   1.012658   2.025316   2.025316
 [918]   3.037975   1.012658  17.215195  35.404449   3.037975   1.012658   1.012658
 [925]   1.012658   1.012658   1.012658   1.012658   1.012658   6.075951   2.025316
 [932]   4.050632   1.012658   1.012658   2.025316   2.025316   1.012658   1.012658
 [939]   1.012658   3.037975   2.025316   2.025316   1.012658   1.012658   1.012658
 [946]  10.126579  10.580620   1.012658   1.012658   1.012658   1.012658   4.050632
 [953]   2.025316   1.012658   1.012658   2.025316   1.012658   1.012658   1.012658
 [960]   2.025316   2.025316   3.037975   1.012658   1.012658   1.012658   1.012658
 [967]   1.012658   1.012658   3.265186   4.494217   1.012658   1.012658   1.012658
 [974]  12.151901   1.012658   1.012658   1.012658   1.012658   2.025316   2.025316
 [981]   1.012658   3.037975   6.075951   1.012658   1.012658   1.012658   1.012658
 [988]   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658   1.012658
 [995]   1.012658   2.025316   1.012658   1.012658   2.025316   3.037975
 [ reached getOption("max.print") -- omitted 1251 entries ]`


I also checked my colleague's data (measured by same instrument, conveted by same method).
`raw_data <- readMSData(files = muyao_cdfs[1:30],mode = "onDisk",msLevel. = 1, centroided. = TRUE)`
`sp <- raw_data[[1]]
> 
> intensity(sp)
  [1]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
  [9]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
 [17]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
 [25]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  4.050632  3.037975
 [33]  1.012658  1.012658  1.012658  7.088608  1.012658  9.905830  1.012658  1.012658
 [41] 17.215195  1.012658  1.012658  7.088608  7.544975  1.012658  1.012658  1.012658
 [49]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
 [57]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658 17.215195
 [65]  1.012658  4.050632  1.012658  1.012658  2.025316  1.012658  3.037975  1.012658
 [73]  1.012658  1.012658  1.012658  1.012658 12.151901  1.012658  4.050632  1.012658
 [81]  1.012658  1.012658  1.012658  2.025316  1.012658  1.012658  1.012658  2.025316
 [89]  2.025316  1.012658  1.012658  1.012658  1.012658  6.556953  1.012658  1.012658
 [97]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[105]  1.012658  2.025316  2.025316  1.012658  9.483589  1.012658  1.012658  2.025316
[113]  5.063290  1.012658  1.012658  1.012658  1.012658  2.025316  1.012658  2.025316
[121]  1.012658  1.012658  1.012658  1.012658  1.012658  3.037975  1.012658  2.025316
[129]  1.012658  1.012658  1.012658  1.012658  2.025316  1.012658  1.012658  2.025316
[137]  1.012658  1.012658  1.012658  1.012658  1.012658  2.025316  1.012658  1.012658
[145]  1.012658  1.012658  1.012658  1.012658  2.025316  1.012658  1.012658  1.012658
[153]  1.012658  1.012658  3.037975  1.012658  1.012658  1.012658  1.012658  1.012658
[161]  1.012658  3.037975  1.012658  1.012658  2.025316  1.012658  2.025316  1.012658
[169]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[177]  1.012658  1.012658  1.012658  1.012658  1.012658  2.025316  1.012658  1.012658
[185]  1.012658  1.012658  1.012658  1.012658  1.012658  2.025316  1.012658  1.012658
[193]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[201]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[209]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[217]  1.012658  2.025316  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[225]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[233]  2.025316  1.012658  1.012658  1.012658  1.012658  1.012658  2.025316  1.012658
[241]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[249]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  2.025316  1.012658
[257]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[265]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  3.037975  1.012658
[273]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[281]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[289]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[297]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[305]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[313]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[321]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[329]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[337]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[345]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[353]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[361]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[369]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[377]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[385]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658
[393]  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658  1.012658`

**Comment by jotsetung** [comment] 2019-03-29 18:00
I've changed the check for centroided data in `findChromPeaks`. Please install the update using:
```r
devtools::install_github("sneumann/xcms", ref = "RELEASE_3_8")
```
and let me know if that fixed your problem.

**Comment by tuhulab** [comment] 2019-03-31 13:08
@jotsetung Hi, Johannes. Good news!!! Now, I do not encounter that bug anymore. Thank you very much.
Could you please simply explain to me, what did you adjust??

**Comment by jotsetung** [comment] 2019-04-01 06:30
The error came simply from the test to check if the input data is centroided. To not slow down things I checked only in the first spectrum of the data set if the data is centroided (based on the m/z values). Now I changed it and rely on the user's input, i.e. if you say it is centroided data (by setting e.g. `centroided(data) <- TRUE`) I believe you and skip the test.

**Comment by jotsetung** [comment] 2019-04-01 06:30
Since the problem is fixed I close this issue - feel free to re-open if needed.

**Closed by jotsetung** 2019-04-01 06:30 UTC
