### ISSUE TITLE
xcms3 -- Error in x$.self$finalize() : attempt to apply non-function

### ISSUE THREAD

**Issue by etrh** [sneumann/xcms#288] opened 2018-06-06 12:10 UTC
I got this error when running the following line of code:

`bpis <- chromatogram(raw_data, aggregationFun = "max")`

```
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
```
Afterwards, when I checked `bpis`, it was not empty and I could even generate the desired plot.

Any idea what this error means? Does it indicate a problem with my files or is it simply a bug?

**Comment by etrh** [comment] 2018-07-13 09:21
Today, I came across this error again. But this time when executing the `findChromPeaks` function.

```
> xdata <- findChromPeaks(raw_data, param = cwp)
Detecting mass traces at 30 ppm ... OK
Detecting chromatographic peaks in 145554 regions of interest ... OK: 6585 found.
Detecting mass traces at 30 ppm ... OK
Detecting chromatographic peaks in 150650 regions of interest ... OK: 6534 found.
Detecting mass traces at 30 ppm ... OK
Detecting chromatographic peaks in 147561 regions of interest ... OK: 6476 found.
Error in x$.self$finalize() : attempt to apply non-function
Detecting mass traces at 30 ppm ... OK
Detecting chromatographic peaks in 152287 regions of interest ... OK: 6669 found.
Detecting mass traces at 30 ppm ... OK
Detecting chromatographic peaks in 142591 regions of interest ... OK: 6581 found.
Detecting mass traces at 30 ppm ... OK
Detecting chromatographic peaks in 146840 regions of interest ... OK: 7353 found.
Detecting mass traces at 30 ppm ... OK
Detecting chromatographic peaks in 147218 regions of interest ... OK: 6619 found.
Error in x$.self$finalize() : attempt to apply non-function
```

**Comment by luckygoh** [comment] 2018-08-27 16:28
Hi,

Stumbled into a slightly similar error using xcms 3.2.0. 
Is the error has noting to worry about as mentioned in previous posts?

`
> ##FEATURE DETECTION
> cwp <- CentWaveParam(ppm = 15, peakwidth = c(10, 30), mzdiff = 0.01, snthresh = 6, integrate = 1, prefilter = c(3, 100),  noise = 2000)
> xdata <- findChromPeaks(raw_data, param = cwp)
Detecting mass traces at 15 ppm ... OK
Detecting chromatographic peaks in 396 regions of interest ... OK: 357 found.
Detecting mass traces at 15 ppm ... OK
Detecting chromatographic peaks in 394 regions of interest ... OK: 368 found.
Detecting mass traces at 15 ppm ... OK
Detecting chromatographic peaks in 491 regions of interest ... OK: 438 found.
Detecting mass traces at 15 ppm ... OK
Detecting chromatographic peaks in 435 regions of interest ... OK: 386 found.
Detecting mass traces at 15 ppm ... OK
Detecting chromatographic peaks in 569 regions of interest ... OK: 507 found.
Detecting mass traces at 15 ppm ... OK
Detecting chromatographic peaks in 430 regions of interest ... OK: 373 found.
Error in (function (x)  : attempt to apply non-function
`

`> ## retention time correction.
> xdata <- adjustRtime(xdata, param = ObiwarpParam(binSize = 0.6))
Sample number 25 used as center sample.
Aligning Diseased 34.mzXML against Control12.mzXML ... Error in (function (x)  : attempt to apply non-function`

**Comment by jotsetung** [comment] 2018-08-30 10:41
I suspect this is all related to some garbage collection related things going on in R (see also issue #305).
@luckygoh , can you reproduce the error, i.e. if you run the peak detection twice, do you get the error each time? The actual *proof* that this is not a problem would be if you manage to run the analysis twice, once with and once without errors and, by comparing the result objects, don't find differences. My problem is that I can not reproduce this on my mac and also not on my linux and windows test systems.

**Comment by etrh** [comment] 2018-09-07 13:13
I also believe this is not really an error and it is safe to ignore it. 

I have been seeing this error a lot lately, and under different circumstances, for example when running `fillChromPeaks`, `findChromPeaks`, etc., but as @jotsetung said, it does not seem to be a problem at all. I have never seen anything strange happen to the end result under any such occasions.

**Comment by AhmedEzatElZowalaty** [comment] 2020-05-31 11:40
I saw the same error while doing Data Trimming on a mass spec data file using the metaboanalyst package. The command is raw_data <- PerformDataTrimming(data_folder_QC,rt.idx = 0.2). 

Data Loaded !
Data Trimming...
MS data Parsing ...
Error in x$.self$finalize() : attempt to apply non-function

The chromatogram plotted fine though.

**Comment by jorainer** [comment] 2020-06-03 06:38
Interesting - so it is most likely related to `mzR` then, because I guess `metaboanalyst` is not using code from `xcms`...

**Comment by andzajan** [comment] 2020-06-03 16:11
Hi @jorainer , it is definitely related to mzR, I am using mzR functionality to extract EIC's and I see this message regularly. 

On top of that, I also see differences in returned EIC values between different R environments. For example, I can run commands I use in unit test locally and generate output. That test runs OK, if I click "Run Tests" for the given file from Rstudio, but fails with `devtools:test()` command.  Also it is passing on TravisCI, but fails in Appveyor and Github-actions. I will try to make an isolated reproducible example of this.

**Comment by stefnoerman** [comment] 2021-11-17 09:31
hi,
i got the same error during the findChromPeaks function. but then after detecting some peaks, i got this error message
![image](https://user-images.githubusercontent.com/94456030/142174410-405ed476-6493-4a89-ab9c-065a17ebec6d.png)

any idea why and how to solve it? thanks

**Comment by jorainer** [comment] 2021-11-17 10:12
Can you please use `register(SerialParam())` before your `findChromPeaks` call and try again - the error message should then hopefully be a little more self-explaining. In parallel processing error messages can be less verbose/detailed.

**Comment by stefnoerman** [comment] 2021-11-17 15:40
hi jorainer, thanks for your advice. 
i did as you said, and now i got this error message. what does it mean?

![image](https://user-images.githubusercontent.com/94456030/142232006-f65a384b-475f-4f07-9c6e-5ef7cb9fe6ff.png)

thanks a lot

**Comment by jorainer** [comment] 2021-11-18 07:24
The `rectUnique` function throws this error. `rectUnique` uses C-code to process the data that is passed along from R. I've never seen such an error before. It could mean that some unexpected values are passed to this function. It's hard to tell what exactly caused the error - would it be possible for you to share the one file with me (or some other file where you get this error) so that I could dig more into it?

**Comment by stefnoerman** [comment] 2021-11-18 08:16
thanks for your answer, jorainer. I got this error while doing peak-picking for RP positive mode, while I didn't get any problem for the same samples in 3 other modes. I don't know which files (among 260 files) caused this error, either. any idea how to check that? thanks

**Comment by rToddler62** [comment] 2022-07-16 00:03
i got this error today - maybe this example might help unravel the problem?  i ran the same script twice, reading data from a different file path each time, using the object "fileloc".  first time no problem, second time this error appeared. Like previous authors, the final result was fine.
  library(raster)
  library(rgdal)
  library(tidyr)
  sclga <- readOGR("Selected_feature_FID_18.shp")
  fdimdf <- data.frame(Date = as.Date(character()), 
                    meanFDI = double(), 
                    stringsAsFactors = FALSE) 
  FileNameList <- read.csv("SampleFileNames 2016-2020.csv", header = FALSE)
  fileloc <- "C:/Scratch/Test loop on sample/Sample FFDI Files 2016-2020/"
    for(i in 1:nrow(FileNameList)){
      ncFile <- paste(fileloc, FileNameList[i,1], sep = "")
      nc <- raster(ncFile)
      fnDate <- as.Date(substr(FileNameList[i,1],5,12), "%Y%m%d")
      masked <- raster::mask(x = nc, mask = sclga)
      fdicropped <- crop(x = masked, y = extent(sclga))
      fdicropped@data@values[fdicropped@data@values==0] <- NA
      fdim <- cellStats(fdicropped, stat = 'mean', na.rm = TRUE)
      temp <- data.frame(fnDate, fdim)
      fdimdf <- rbind(fdimdf, temp)
    } 
Loading required namespace: ncdf4
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function

**Comment by jorainer** [comment] 2022-07-26 05:39
These messages (*Error in x$.self...* and *Errior in (function...*) occurr randomly and we did not yet find a way to get rid of those. My best guess is that R tries to call a finalizing function on an object that was already deleted. And since this happens only in combination with code from the `mzR` package, which uses the proteowizard C++ libraries, I guess it has to do something with that (C++, Boost, R).

**Comment by bthetford** [comment] 2022-08-31 01:36
I keep getting this exact error when trying to use the R package glcm, when trying to analyze rasters for texture. It seems to only happen when the raster I put in is over 500 MB large. Within a loop:
`  calText[[i]] <- glcm(calImages[[i]], 
              window = c(windowSize, windowSize), 
              shift=list(c(0,1), c(1,1), c(1,0), c(1,-1)), 
              statistics = c("mean", "variance", "homogeneity", "contrast", "dissimilarity", "entropy", 
"second_moment", "correlation")`
gives
`Error in x$.self$finalize() : attempt to apply non-function`
and doesn't continue on to generate the texture rasters. Can't ignore it this time!
This was with an 800 MB tif file, but with a 200 MB file I don't get the error and the function works.

**Comment by eddelbuettel** [comment] 2022-09-27 12:50
Thanks -- the install command the Rcpp Core team recommend is

   install.packages("Rcpp", repos="https://rcppcore.github.io/drat")

as we make explicit releases to our drat which we consider preferable to random repo snapshots.

**Comment by stanstrup** [comment] 2022-09-28 09:52
Great that this was finally fixed. Thanks!
This always led to questions from our students.

**Comment by jorainer** [comment] 2022-09-29 08:32
Closing this issue now as the new `Rcpp` version fixes this.

**Closed by jorainer** 2022-09-29 08:32 UTC
